name: 'rs_medallion'
version: '1.0.0'
config-version: 2

profile: 'rs_medallion'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

tests:
  +severity: warn

on-run-start:
  - "{{ create_audit_log_table() }}"

on-run-end:
  - "{{ capture_run_results() }}"

models:
    logging:
        +enabled: false
    rs_medallion:
        audit:
            database: AUDIT
            schema: DBT_TRADATA_TRANSFORMATION
            materialized: incremental
        bronze:
            materialized: incremental
            es_eqai:
                database: EQAI
                schema: ODS
            workday:
                database: WORKDAY
                schema: ODS
        silver:
            materialized: table
            cdm:
                database: CDM
                schema: WORKFORCE
                tags: ["cdm", "workforce"]
            core:
                database: CORE
                shared_dims:
                    database: CORE
                    schema: SHARED_DIMS
                    tags: ["core", "shared_dims"]
                workforce:
                    database: CORE
                    schema: WORKFORCE
                    tags: ["core", "workforce"]