name: 'rs_medallion'
version: '1.0.0'
config-version: 2

profile: 'rs_medallion'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  rs_medallion:
    audit:
      +materialized: table
    bronze:
      +materialized: incremental
      es_eqai:
        +schema: ODS
        +tags: ["ods", "es_eqai"]
      workday:
        +schema: ODS
        +tags: ["ods", "workday"]
    silver:
      +materialized: table
      cdm:
        workforce:
          +schema: CDM
          +tags: ["cdm", "workforce"]
      core:
        confirmed_dimensions:
          +schema: CORE
          +tags: ["core", "confirmed_dimensions"]
        workforce:
          +schema: CORE
          +tags: ["core", "workforce"]
    gold:
      +materialized: table
