{{
    config(
        materialized='incremental',
        unique_key='ODS_IFP_CDPARTB_PK',
        merge_no_update_columns = ['ODS_INS_BATCH_ID','ODS_INSERT_TIMESTAMP','SRC_CREATE_DTM'],
        merge_condition="DBT_INTERNAL_SOURCE.HASH_CHANGE != DBT_INTERNAL_DEST.HASH_CHANGE",
        tags=["ods","infopro","scheduled-every30min","data-observe"],
	pre_hook=" {% if is_incremental() %}
                EXECUTE IMMEDIATE $$
                 BEGIN
                 IF (EXISTS(SELECT * FROM {{ this.database }}.information_schema.tables WHERE table_schema = UPPER('{{ this.schema }}') AND table_name = UPPER('{{ this.identifier }}'))) THEN
                 UPDATE {{ this }}
                 SET SRC_ACTION_CD='D',
                     SRC_DEL_IND='Y',
                     SRC_LAST_UPDATE_DTM=CURRENT_TIMESTAMP,
                     ODS_UPD_BATCH_ID=TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDDHH24MISSFF3')),
                     ODS_UPDATE_TIMESTAMP=CURRENT_TIMESTAMP,
                     OPERATION_TYPE='DELETE'
                 WHERE ODS_IFP_CDPARTB_PK IN (
                     SELECT {{ generate_surrogate_key([trim_string('DTL__BI_COMPANY'),trim_string('DTL__BI_ACCOUNT')]) }}
                     FROM {{ source('STAGING','STG_IFP_CDPARTB') }}
                     WHERE PRIMARY_KEY_CHANGE='Y'
                     AND to_timestamp_tz(SUBSTRING(DTL__CAPXTIMESTAMP,1,17),'YYYYMMDDHHMISSFF') >= '{{ get_max_event_time('SRC_LAST_UPDATE_DTM') }}'
                 );
                 COMMIT;
                 END IF;
                END;
                $$;
                {% endif %}"
        )
}}

WITH CTE_BATCH_ID AS (
    SELECT TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')) AS BATCH_ID,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP_NTZ) AS BATCH_TIMESTAMP
)

{% if is_incremental() %}

--> Grab all the records newer than last update
,CTE_SOURCE_RECORDS AS (
        SELECT * FROM {{ source('STAGING','STG_IFP_CDPARTB') }}
        where
        to_timestamp_tz(SUBSTRING(TRIM(DTL__CAPXTIMESTAMP),1,17),'YYYYMMDDHHMISSFF')  >= '{{ get_max_event_time('SRC_LAST_UPDATE_DTM') }}'
)

,CTE_DEDUP as (
  select *, ROW_NUMBER() OVER(PARTITION BY COMPANY,ACCOUNT ORDER BY DTL__CAPXTIMESTAMP DESC) AS ROW_NUM
  from CTE_SOURCE_RECORDS
  qualify ROW_NUM=1
)

,CTE_TEMP as (
select CTE_SOURCE_RECORDS.DTL__BI_COMPANY, CTE_SOURCE_RECORDS.DTL__BI_ACCOUNT from 
CTE_SOURCE_RECORDS LEFT JOIN CTE_DEDUP 
 ON CTE_SOURCE_RECORDS.DTL__BI_COMPANY=CTE_DEDUP.COMPANY
 AND CTE_SOURCE_RECORDS.DTL__BI_ACCOUNT=CTE_DEDUP.ACCOUNT
 where CTE_SOURCE_RECORDS.PRIMARY_KEY_CHANGE  = 'Y'
AND (TO_NUMBER(CTE_SOURCE_RECORDS.PK_LZ_IFP_CDPARTB_ID) >=  TO_NUMBER(CTE_DEDUP.PK_LZ_IFP_CDPARTB_ID) OR TO_NUMBER(CTE_DEDUP.PK_LZ_IFP_CDPARTB_ID) IS NULL)
)

,CTE_FINAL as (
select * from CTE_DEDUP where CONCAT_WS(',',COMPANY,ACCOUNT) in (
select CONCAT_WS(',',COMPANY,ACCOUNT) from CTE_DEDUP
except 
select CONCAT_WS(',',DTL__BI_COMPANY,DTL__BI_ACCOUNT) from CTE_TEMP)
)

--> Current Delta data capture from STG table
,CTE_TRANSFORMED AS (
SELECT
        {{ generate_surrogate_key([trim_string('COMPANY'),trim_string('ACCOUNT')])}} as ODS_IFP_CDPARTB_PK ,
        CAST(CONCAT({{ trim_string('COMPANY')}},'-',{{ trim_string('ACCOUNT')}}) AS VARCHAR(50)) AS ODS_IFP_CDPARTB_COMPOSITE_KEY,
        STG_IFP_CDPARTB_PK,
        {{ trim_string('DTL__CAPXUSER') }} AS SRC_CDC_LIB,
        {{ trim_string('COMPANY')}} AS COMPANY,
        {{ trim_string('ACCOUNT')}} AS ACCOUNT,
        {{ trim_string('SORT_NAME')}} AS SORT_NAME,
        CAST(AGING_DAYS_1 AS NUMBER(3,0)) AS AGING_DAYS_1,
        CAST(AGING_DAYS_2 AS NUMBER(3,0)) AS AGING_DAYS_2,
        CAST(AGING_DAYS_3 AS NUMBER(3,0)) AS AGING_DAYS_3,
        CAST(AGING_DAYS_4 AS NUMBER(3,0)) AS AGING_DAYS_4,
        CAST(AGING_DAYS_5 AS NUMBER(3,0)) AS AGING_DAYS_5,
        CAST(AGING_DAYS_6 AS NUMBER(3,0)) AS AGING_DAYS_6,
        CAST(AGING_AMOUNT_1 AS NUMBER(13,2)) AS AGING_AMOUNT_1,
        CAST(AGING_AMOUNT_2 AS NUMBER(13,2)) AS AGING_AMOUNT_2,
        CAST(AGING_AMOUNT_3 AS NUMBER(13,2)) AS AGING_AMOUNT_3,
        CAST(AGING_AMOUNT_4 AS NUMBER(13,2)) AS AGING_AMOUNT_4,
        CAST(AGING_AMOUNT_5 AS NUMBER(13,2)) AS AGING_AMOUNT_5,
        CAST(AGING_AMOUNT_6 AS NUMBER(13,2)) AS AGING_AMOUNT_6,
        CAST(AGING_AMOUNT_7 AS NUMBER(13,2)) AS AGING_AMOUNT_7,
        CAST(UNREFERENCED_AMOUNT AS NUMBER(13,2)) AS UNREFERENCED_AMOUNT,
        CAST(UNAPPLIED_AMOUNT AS NUMBER(13,2)) AS UNAPPLIED_AMOUNT,
        CAST(CREDIT_AMOUNT AS NUMBER(13,2)) AS CREDIT_AMOUNT,
        CAST(DEBIT_AMOUNT AS NUMBER(13,2)) AS DEBIT_AMOUNT,
        {{ trim_string('CURRENCY_CODE')}} AS CURRENCY_CODE,
        {{ trim_string('AR_TYPE')}} AS AR_TYPE,
        {{ trim_string('AGING_CATEGORY_1')}} AS AGING_CATEGORY_1,
        {{ trim_string('AGING_CATEGORY_2')}} AS AGING_CATEGORY_2,
        {{ trim_string('AGING_CATEGORY_3')}} AS AGING_CATEGORY_3,
        {{ trim_string('AGING_CATEGORY_4')}} AS AGING_CATEGORY_4,
        {{ trim_string('AGING_CATEGORY_5')}} AS AGING_CATEGORY_5,
        {{ trim_string('AGING_CATEGORY_6')}} AS AGING_CATEGORY_6,
        {{ trim_string('AGING_CATEGORY_7')}} AS AGING_CATEGORY_7,
        CAST(TOTAL_AR AS NUMBER(15,2)) AS TOTAL_AR,
        {{ trim_string('CUSTOMER_CATEGORY')}} AS CUSTOMER_CATEGORY,
        {{ trim_string('CUSTOMER_CATEGORY_DESCRIPTION')}} AS CUSTOMER_CATEGORY_DESC,
        {{ trim_string('INVOICE_DAY')}} AS INVOICE_DAY,
        {{ trim_string('QUICK_PAY_ENR')}} AS QUICK_PAY_ENR,
        {{ trim_string('QUICK_PAY_ENROLLMENT_TYPE')}} AS QUICK_PAY_ENROLLMENT_TYPE,
        {{ trim_string('QUICK_PAY_DESCRIPTION')}} AS QUICK_PAY_DESC,
        ACCOUNT_START_DATE AS ACCOUNT_START_DATE_ORIG,
        TRY_TO_TIMESTAMP(TO_VARCHAR(ACCOUNT_START_DATE), 'YYYYMMDD') AS ACCOUNT_START_DATE,
        ACCOUNT_CLOSE_DATE AS ACCOUNT_CLOSE_DATE_ORIG,
        TRY_TO_TIMESTAMP(TO_VARCHAR(ACCOUNT_CLOSE_DATE), 'YYYYMMDD') AS ACCOUNT_CLOSE_DATE,
        {{ trim_string('INVOICE1_NUMBER')}} AS INVOICE1_NUMBER,
        {{ trim_string('INVOICE2_NUMBER')}} AS INVOICE2_NUMBER,
        {{ trim_string('INVOICE3_NUMBER')}} AS INVOICE3_NUMBER,
        {{ trim_string('INVOICE4_NUMBER')}} AS INVOICE4_NUMBER,
        {{ trim_string('INVOICE5_NUMBER')}} AS INVOICE5_NUMBER,
        {{ trim_string('INVOICE6_NUMBER')}} AS INVOICE6_NUMBER,
        {{ trim_string('RR_VENDOR_ID')}} AS RR_VENDOR_ID,
        {{ trim_string('RR_VENDOR_ID_DESC')}} AS RR_VENDOR_ID_DESC,
        RR_START_DATE AS RR_START_DATE_ORIG,
        TRY_TO_TIMESTAMP(TO_VARCHAR(RR_START_DATE), 'YYYYMMDD') AS RR_START_DATE,
        RR_ACTIVE_DATE AS RR_ACTIVE_DATE_ORIG,
        TRY_TO_TIMESTAMP(TO_VARCHAR(RR_ACTIVE_DATE), 'YYYYMMDD') AS RR_ACTIVE_DATE,
        {{ trim_string('ACCOUNT_NAME')}} AS ACCOUNT_NAME,
        {{ trim_string('ACCOUNT_ADDRESS1')}} AS ACCOUNT_ADDRESS1,
        {{ trim_string('ACCOUNT_ADDRESS2')}} AS ACCOUNT_ADDRESS2,
        {{ trim_string('ACCOUNT_ADDRESS3')}} AS ACCOUNT_ADDRESS3,
        {{ trim_string('ACCOUNT_CITY')}} AS ACCOUNT_CITY,
        {{ trim_string('ACCOUNT_STATE')}} AS ACCOUNT_STATE,
        {{ trim_string('ACCOUNT_ZIP')}} AS ACCOUNT_ZIP,
        {{ trim_string('ACCOUNT_COUNTRY')}} AS ACCOUNT_COUNTRY,
        {{ trim_string('ACCOUNT_PHONE')}} AS ACCOUNT_PHONE,
        CAST(ACCOUNT_PHONE_EXT AS NUMBER(4,0)) AS ACCOUNT_PHONE_EXT,
        {{ trim_string('ACCOUNT_CARE_OF')}} AS ACCOUNT_CARE_OF,
        {{ trim_string('ACCOUNT_SUSPEND_FLAG')}} AS ACCOUNT_SUSPEND_FLAG,
        ACCOUNT_SUSPEND_DATE AS ACCOUNT_SUSPEND_DATE_ORIG,
        TRY_TO_TIMESTAMP(TO_VARCHAR(ACCOUNT_SUSPEND_DATE), 'YYYYMMDD') AS ACCOUNT_SUSPEND_DATE,
        {{ trim_string('ACCOUNT_PAPERLESS_FLAG')}} AS ACCOUNT_PAPERLESS_FLAG,
        {{ trim_string('NATIONAL_ACCOUNT_FLAG')}} AS NATIONAL_ACCOUNT_FLAG,
        {{ trim_string('MUNICIPAL_FRANCHISE_FLAG')}} AS MUNICIPAL_FRANCHISE_FLAG,
        {{ trim_string('MUNICIPAL_FRANCHISE_DESC')}} AS MUNICIPAL_FRANCHISE_DESC,
        {{ trim_string('SUMMARY_BILLED_CONTRACT_FLAG')}} AS SUMMARY_BILLED_CONTRACT_FLAG,
        {{ trim_string('CREATE_USER')}} AS CREATE_USER,
        {{ trim_string('CREATE_PROGRAM')}} AS CREATE_PROGRAM,
        {{ trim_string('UPDATE_USER')}} AS UPDATE_USER,
        {{ trim_string('UPDATE_PROGRAM')}} AS UPDATE_PROGRAM,
        {{ trim_string('ACTIVERECORDFLAG')}} AS ACTIVERECORDFLAG,
        CAST(CREATE_DATETIME_STAMP AS TIMESTAMP_NTZ(9)) AS CREATE_DATETIME_STAMP,
        CAST(UPDATE_DATETIME_STAMP AS TIMESTAMP_NTZ(9)) AS UPDATE_DATETIME_STAMP,
        CAST(UPDATE_DATETIME_STAMP_AR AS TIMESTAMP_NTZ(9)) AS UPDATE_DATETIME_STAMP_AR,
        CAST(UPDATE_DATETIME_STAMP_ACCT AS TIMESTAMP_NTZ(9)) AS UPDATE_DATETIME_STAMP_ACCT,
        {{ trim_string('BROKER_FLAG')}} AS BROKER_FLAG,
        TRY_TO_TIMESTAMP(TO_VARCHAR(NEXT_INV_DATE), 'YYYYMMDD') AS NEXT_INV_DATE,
        NEXT_INV_DATE AS NEXT_INV_DATE_ORIG,
        SOURCE_SYSTEM,
        CAST('STG_IFP_CDPARTB' AS VARCHAR(200)) AS SOURCE_TABLE,
        to_timestamp_ntz(to_timestamp_tz(SUBSTRING(TRIM(DTL__CAPXTIMESTAMP),1,17),'YYYYMMDDHHMISSFF')) AS SRC_CREATE_DTM,
        to_timestamp_ntz(to_timestamp_tz(SUBSTRING(TRIM(DTL__CAPXTIMESTAMP),1,17),'YYYYMMDDHHMISSFF')) AS SRC_LAST_UPDATE_DTM,
        TRIM(DTL__CAPXACTION) AS SRC_ACTION_CD,
        CASE WHEN TRIM(DTL__CAPXACTION) = 'D' THEN 'Y' ELSE 'N' END AS SRC_DEL_IND,
        CAST(BATCH_ID AS BIGINT) AS ODS_INS_BATCH_ID,
        CAST(BATCH_ID AS BIGINT) AS ODS_UPD_BATCH_ID,
        BATCH_TIMESTAMP AS ODS_INSERT_TIMESTAMP,
        BATCH_TIMESTAMP AS ODS_UPDATE_TIMESTAMP,
        CAST(STG_INSERT_TIMESTAMP AS TIMESTAMP_NTZ) AS STG_INSERT_TIMESTAMP,
        CASE WHEN SRC_DEL_IND = 'Y' THEN 'DELETE' ELSE 'INSERT' END AS OPERATION_TYPE, --overwrite operation type as UPDATE/DELETE in merge operation
        CAST(NULL AS VARCHAR(20)) AS DQ_STATUS,
        CAST(NULL AS VARCHAR(500)) AS DQ_ERROR_CODE,
        CAST(NULL AS VARCHAR(2000)) AS DQ_ERROR_MESSAGE
from CTE_FINAL
LEFT JOIN CTE_BATCH_ID ON 1=1
)

{% else %}

,CTE_HISTORICAL AS (
SELECT
        {{ generate_surrogate_key([trim_string('COMPANY'),trim_string('ACCOUNT')]) }} AS ODS_IFP_CDPARTB_PK,
        CAST(CONCAT({{ trim_string('COMPANY') }},'-',{{ trim_string('ACCOUNT') }}) AS VARCHAR(50)) AS ODS_IFP_CDPARTB_COMPOSITE_KEY,
        CAST(NULL AS NUMBER) AS STG_IFP_CDPARTB_PK,
        {{ trim_string('SYS_CDC_LIB') }} AS SRC_CDC_LIB,
        {{ trim_string('COMPANY') }} AS COMPANY,
        {{ trim_string('ACCOUNT') }} AS ACCOUNT,
        {{ trim_string('SORT_NAME') }} AS SORT_NAME,
        CAST(AGING_DAYS_1 AS NUMBER(3,0)) AS AGING_DAYS_1,
        CAST(AGING_DAYS_2 AS NUMBER(3,0)) AS AGING_DAYS_2,
        CAST(AGING_DAYS_3 AS NUMBER(3,0)) AS AGING_DAYS_3,
        CAST(AGING_DAYS_4 AS NUMBER(3,0)) AS AGING_DAYS_4,
        CAST(AGING_DAYS_5 AS NUMBER(3,0)) AS AGING_DAYS_5,
        CAST(AGING_DAYS_6 AS NUMBER(3,0)) AS AGING_DAYS_6,
        CAST(AGING_AMOUNT_1 AS NUMBER(13,2)) AS AGING_AMOUNT_1,
        CAST(AGING_AMOUNT_2 AS NUMBER(13,2)) AS AGING_AMOUNT_2,
        CAST(AGING_AMOUNT_3 AS NUMBER(13,2)) AS AGING_AMOUNT_3,
        CAST(AGING_AMOUNT_4 AS NUMBER(13,2)) AS AGING_AMOUNT_4,
        CAST(AGING_AMOUNT_5 AS NUMBER(13,2)) AS AGING_AMOUNT_5,
        CAST(AGING_AMOUNT_6 AS NUMBER(13,2)) AS AGING_AMOUNT_6,
        CAST(AGING_AMOUNT_7 AS NUMBER(13,2)) AS AGING_AMOUNT_7,
        CAST(UNREFERENCED_AMOUNT AS NUMBER(13,2)) AS UNREFERENCED_AMOUNT,
        CAST(UNAPPLIED_AMOUNT AS NUMBER(13,2)) AS UNAPPLIED_AMOUNT,
        CAST(CREDIT_AMOUNT AS NUMBER(13,2)) AS CREDIT_AMOUNT,
        CAST(DEBIT_AMOUNT AS NUMBER(13,2)) AS DEBIT_AMOUNT,
        {{ trim_string('CURRENCY_CODE') }} AS CURRENCY_CODE,
        {{ trim_string('AR_TYPE') }} AS AR_TYPE,
        {{ trim_string('AGING_CATEGORY_1') }} AS AGING_CATEGORY_1,
        {{ trim_string('AGING_CATEGORY_2') }} AS AGING_CATEGORY_2,
        {{ trim_string('AGING_CATEGORY_3') }} AS AGING_CATEGORY_3,
        {{ trim_string('AGING_CATEGORY_4') }} AS AGING_CATEGORY_4,
        {{ trim_string('AGING_CATEGORY_5') }} AS AGING_CATEGORY_5,
        {{ trim_string('AGING_CATEGORY_6') }} AS AGING_CATEGORY_6,
        {{ trim_string('AGING_CATEGORY_7') }} AS AGING_CATEGORY_7,
        CAST(TOTAL_AR AS NUMBER(15,2)) AS TOTAL_AR,
        {{ trim_string('CUSTOMER_CATEGORY') }} AS CUSTOMER_CATEGORY,
        {{ trim_string('CUSTOMER_CATEGORY_DESC') }} AS CUSTOMER_CATEGORY_DESC,
        {{ trim_string('INVOICE_DAY') }} AS INVOICE_DAY,
        {{ trim_string('QUICK_PAY_ENR') }} AS QUICK_PAY_ENR,
        {{ trim_string('QUICK_PAY_ENROLLMENT_TYPE') }} AS QUICK_PAY_ENROLLMENT_TYPE,
        {{ trim_string('QUICK_PAY_DESC') }} AS QUICK_PAY_DESC,
        CAST(ACCOUNT_START_DATE_ORIG AS NUMBER(10,0)) AS ACCOUNT_START_DATE_ORIG,
        CAST(ACCOUNT_START_DATE AS TIMESTAMP_NTZ) AS ACCOUNT_START_DATE,
        CAST(ACCOUNT_CLOSE_DATE_ORIG AS NUMBER(10,0)) AS ACCOUNT_CLOSE_DATE_ORIG,
        CAST(ACCOUNT_CLOSE_DATE AS TIMESTAMP_NTZ) AS ACCOUNT_CLOSE_DATE,
        {{ trim_string('INVOICE1_NUMBER') }} AS INVOICE1_NUMBER,
        {{ trim_string('INVOICE2_NUMBER') }} AS INVOICE2_NUMBER,
        {{ trim_string('INVOICE3_NUMBER') }} AS INVOICE3_NUMBER,
        {{ trim_string('INVOICE4_NUMBER') }} AS INVOICE4_NUMBER,
        {{ trim_string('INVOICE5_NUMBER') }} AS INVOICE5_NUMBER,
        {{ trim_string('INVOICE6_NUMBER') }} AS INVOICE6_NUMBER,
        {{ trim_string('RR_VENDOR_ID') }} AS RR_VENDOR_ID,
        {{ trim_string('RR_VENDOR_ID_DESC') }} AS RR_VENDOR_ID_DESC,
        CAST(RR_START_DATE_ORIG AS NUMBER(10,0)) AS RR_START_DATE_ORIG,
        CAST(RR_START_DATE AS TIMESTAMP_NTZ) AS RR_START_DATE,
        CAST(RR_ACTIVE_DATE_ORIG AS NUMBER(10,0)) AS RR_ACTIVE_DATE_ORIG,
        CAST(RR_ACTIVE_DATE AS TIMESTAMP_NTZ) AS RR_ACTIVE_DATE,
        {{ trim_string('ACCOUNT_NAME') }} AS ACCOUNT_NAME,
        {{ trim_string('ACCOUNT_ADDRESS1') }} AS ACCOUNT_ADDRESS1,
        {{ trim_string('ACCOUNT_ADDRESS2') }} AS ACCOUNT_ADDRESS2,
        {{ trim_string('ACCOUNT_ADDRESS3') }} AS ACCOUNT_ADDRESS3,
        {{ trim_string('ACCOUNT_CITY') }} AS ACCOUNT_CITY,
        {{ trim_string('ACCOUNT_STATE') }} AS ACCOUNT_STATE,
        {{ trim_string('ACCOUNT_ZIP') }} AS ACCOUNT_ZIP,
        {{ trim_string('ACCOUNT_COUNTRY') }} AS ACCOUNT_COUNTRY,
        {{ trim_string('ACCOUNT_PHONE') }} AS ACCOUNT_PHONE,
        CAST(ACCOUNT_PHONE_EXT AS NUMBER(4,0)) AS ACCOUNT_PHONE_EXT,
        {{ trim_string('ACCOUNT_CARE_OF') }} AS ACCOUNT_CARE_OF,
        {{ trim_string('ACCOUNT_SUSPEND_FLAG') }} AS ACCOUNT_SUSPEND_FLAG,
        CAST(ACCOUNT_SUSPEND_DATE_ORIG AS NUMBER(10,0)) AS ACCOUNT_SUSPEND_DATE_ORIG,
        CAST(ACCOUNT_SUSPEND_DATE AS TIMESTAMP_NTZ) AS ACCOUNT_SUSPEND_DATE,
        {{ trim_string('ACCOUNT_PAPERLESS_FLAG') }} AS ACCOUNT_PAPERLESS_FLAG,
        {{ trim_string('NATIONAL_ACCOUNT_FLAG') }} AS NATIONAL_ACCOUNT_FLAG,
        {{ trim_string('MUNICIPAL_FRANCHISE_FLAG') }} AS MUNICIPAL_FRANCHISE_FLAG,
        {{ trim_string('MUNICIPAL_FRANCHISE_DESC') }} AS MUNICIPAL_FRANCHISE_DESC,
        {{ trim_string('SUMMARY_BILLED_CONTRACT_FLAG') }} AS SUMMARY_BILLED_CONTRACT_FLAG,
        {{ trim_string('CREATE_USER') }} AS CREATE_USER,
        {{ trim_string('CREATE_PROGRAM') }} AS CREATE_PROGRAM,
        {{ trim_string('UPDATE_USER') }} AS UPDATE_USER,
        {{ trim_string('UPDATE_PROGRAM') }} AS UPDATE_PROGRAM,
        {{ trim_string('ACTIVERECORDFLAG') }} AS ACTIVERECORDFLAG,
        CAST(CREATE_DATETIME_STAMP AS TIMESTAMP_NTZ) AS CREATE_DATETIME_STAMP,
        CAST(UPDATE_DATETIME_STAMP AS TIMESTAMP_NTZ) AS UPDATE_DATETIME_STAMP,
        CAST(UPDATE_DATETIME_STAMP_AR AS TIMESTAMP_NTZ) AS UPDATE_DATETIME_STAMP_AR,
        CAST(UPDATE_DATETIME_STAMP_ACCT AS TIMESTAMP_NTZ) AS UPDATE_DATETIME_STAMP_ACCT,
        {{ trim_string('BROKER_FLAG') }} AS BROKER_FLAG,
        CAST(NEXT_INV_DATE AS TIMESTAMP_NTZ) AS NEXT_INV_DATE,
        CAST(NEXT_INV_DATE_ORIG AS NUMBER(10,0)) AS NEXT_INV_DATE_ORIG,
        CAST('Infopro' AS VARCHAR(50)) AS SOURCE_SYSTEM,
        CAST('ODS_IFP_CDPARTB_HIST' AS VARCHAR(200)) AS SOURCE_TABLE,
        CAST(SYS_CDC_DTM AS TIMESTAMP_NTZ) AS SRC_CREATE_DTM,
        CAST(SYS_CDC_DTM AS TIMESTAMP_NTZ) AS SRC_LAST_UPDATE_DTM,
        CAST(SYS_ACTION_CD AS VARCHAR(1)) AS SRC_ACTION_CD,
        CAST(SYS_DEL_IND AS VARCHAR(1)) AS SRC_DEL_IND,
        CAST(BATCH_ID AS BIGINT) AS ODS_INS_BATCH_ID,
        CAST(BATCH_ID AS BIGINT) AS ODS_UPD_BATCH_ID,
        BATCH_TIMESTAMP AS ODS_INSERT_TIMESTAMP,
        BATCH_TIMESTAMP AS ODS_UPDATE_TIMESTAMP,
        CAST(STG_INSERT_TIMESTAMP AS TIMESTAMP_NTZ) AS STG_INSERT_TIMESTAMP,
        CASE WHEN SYS_DEL_IND = 'Y' THEN 'DELETE' ELSE 'INSERT' END AS OPERATION_TYPE,
        CAST(NULL AS VARCHAR(20)) AS DQ_STATUS,
        CAST(NULL AS VARCHAR(500)) AS DQ_ERROR_CODE,
        CAST(NULL AS VARCHAR(2000)) AS DQ_ERROR_MESSAGE
FROM INFOPRO.HISTORY.ODS_IFP_CDPARTB_HIST
CROSS JOIN CTE_BATCH_ID
)

{% endif %}

SELECT
        *,
        {{ generate_hash_change( relation = this) }} AS HASH_CHANGE,
        {{ generate_hash_full( relation = this) }} AS HASH_FULL
FROM {% if is_incremental() %}CTE_TRANSFORMED{% else %}CTE_HISTORICAL{% endif %}






