{{
    config(
        materialized='incremental',
        unique_key='CDM_ACCOUNT_PK',
        on_schema_change='append_new_columns',
        merge_no_update_columns = ['CDM_INSERT_TIMESTAMP','CDM_INS_BATCH_ID'],
        merge_condition="DBT_INTERNAL_SOURCE.HASH_CHANGE != DBT_INTERNAL_DEST.HASH_CHANGE",
        tags=["cdm","customer","scheduled-nightly","data-observe"]
    )
}}


WITH CTE_BATCH_ID as (
    select TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')) as BATCH_ID , CURRENT_TIMESTAMP AS TIME_STAMP
)

,ETL_PROFITABILITY_XREF as
  (SELECT ID, MARKET_VERTICAL_DESCRIPTION, MARKET_SUB_VERTICAL_DESCRIPTION, MARKET_SUB_VERTICAL_CODE
    FROM (VALUES
            (2,'Manufacturing','Environmental','ENV01'),
            (1,'Manufacturing','Manufacturing','MFG01')
          ) AS V1 (ID,MARKET_VERTICAL_DESCRIPTION, MARKET_SUB_VERTICAL_DESCRIPTION, MARKET_SUB_VERTICAL_CODE)
  ) 

-- ============================================
-- Pattern 1: Identify changed accounts from ALL source tables BEFORE joining
-- ============================================
{% if is_incremental() %}
, CTE_CHANGED_ACCOUNTS AS (
    -- ARPCU changes
    SELECT DISTINCT CUCO AS INFOPRO_DIVISION_NUMBER, CUCUNO AS ACCOUNT_NUMBER
    FROM {{ ref('ODS_IFP_ARPCU') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_ARPCU) FROM {{ this }} t)

    UNION

    -- BIPCU changes
    SELECT DISTINCT CUCOMP, CUACCT
    FROM {{ ref('ODS_IFP_BIPCU') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_BIPCU) FROM {{ this }} t)

    UNION

    -- BIPIF changes
    SELECT DISTINCT IFCOMP, IFACCT
    FROM {{ ref('ODS_IFP_BIPIF') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_BIPIF) FROM {{ this }} t)

    UNION

    -- ARPCC changes
    SELECT DISTINCT CCCO, CCCUNO
    FROM {{ ref('ODS_IFP_ARPCC') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_ARPCC) FROM {{ this }} t)

    UNION

    -- CDPARTB changes
    SELECT DISTINCT Company, Account
    FROM {{ ref('ODS_IFP_CDPARTB') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_CDPARTB) FROM {{ this }} t)

    UNION

    -- CUPCST01 changes
    SELECT DISTINCT CST_COMP, CST_ACCT
    FROM {{ ref('ODS_IFP_CUPCST01') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_CUPCST01) FROM {{ this }} t)

    UNION

    -- BIPIFE changes
    SELECT DISTINCT FECOMP, FEACCT
    FROM {{ ref('ODS_IFP_BIPIFE') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_BIPIFE) FROM {{ this }} t)

    UNION

    -- CUPCUA changes (account group)
    SELECT DISTINCT UACONO, UAACCT
    FROM {{ ref('ODS_IFP_CUPCUA') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_CUPCUA) FROM {{ this }} t)

    UNION

    -- CUPCUG changes (account group detail)
    SELECT DISTINCT CUPCUA.UACONO, CUPCUA.UAACCT
    FROM {{ ref('ODS_IFP_CUPCUG') }} CUPCUG
    INNER JOIN {{ ref('ODS_IFP_CUPCUA') }} CUPCUA ON CUPCUG.UGACGRPID = CUPCUA.UAACGRPID
    WHERE CUPCUG.ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_CUPCUG) FROM {{ this }} t)

    UNION

    -- BIPAS changes
    SELECT DISTINCT ASCOMP, ASACCT
    FROM {{ ref('ODS_IFP_BIPAS') }}
    WHERE ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_BIPAS) FROM {{ this }} t WHERE t.UPDATE_TIMESTAMP_ODS_IFP_BIPAS IS NOT NULL)

    UNION

    -- SFDC changes – resolve back to ARPCU keys via the join logic
    SELECT DISTINCT ARPCU.CUCO, ARPCU.CUCUNO
    FROM {{ ref('ODS_SFDC_ACCOUNT') }} SFDC
    INNER JOIN {{ ref('ODS_IFP_ARPCU') }} ARPCU
        ON ARPCU.CUCO = SFDC.INFOPRO_NUMBER__C
        AND LPAD(ARPCU.CUCUNO, 7, '0') = LPAD(TRIM(SPLIT_PART(SFDC.INFOPRO_ACCOUNT_NUMBER__C, '/',2)), 7, '0')
    WHERE SFDC.ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_SFDC_ACCOUNT) FROM {{ this }} t)
      AND SFDC.ISDELETED = 0 AND SFDC.INFOPRO_NUMBER__C IS NOT NULL AND SFDC.ACCOUNTNUMBER IS NOT NULL

    UNION

    -- ARPCR changes – resolve back to account keys via ARPCC
    SELECT DISTINCT ARPCC.CCCO, ARPCC.CCCUNO
    FROM {{ ref('ODS_IFP_ARPCR') }} ARPCR
    INNER JOIN {{ ref('ODS_IFP_ARPCC') }} ARPCC ON ARPCC.CCCRPC = ARPCR.CRCRPC
    WHERE ARPCR.ODS_UPDATE_TIMESTAMP > (SELECT MAX(t.UPDATE_TIMESTAMP_ODS_IFP_ARPCR) FROM {{ this }} t)
)
{% endif %}

-- ============================================
-- Source CTEs – filtered to changed accounts on incremental runs
-- ============================================
,CTE_SFDC AS (
    SELECT 
        ACCOUNTNUMBER,
        INFOPRO_ACCOUNT_NUMBER__C,
        INFOPRO_NUMBER__C,  
        MY_RESOURCE_CUSTOMER__C, 
        MY_RESOURCE_ENROLLMENT_DATE__C,
        ROW_NUMBER() over(partition by accountnumber order by createddate desc) as rn,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_SFDC_ACCT,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_SFDC_ACCT,
        ODS_SFDC_ACCOUNT_PK

    FROM {{ ref('ODS_SFDC_ACCOUNT') }}
    WHERE ISDELETED = 0  AND INFOPRO_NUMBER__C IS NOT NULL 
    AND ACCOUNTNUMBER IS NOT NULL
    {% if is_incremental() %}
        AND (INFOPRO_NUMBER__C, LPAD(TRIM(SPLIT_PART(INFOPRO_ACCOUNT_NUMBER__C, '/',2)), 7, '0'))
        IN (SELECT INFOPRO_DIVISION_NUMBER, LPAD(ACCOUNT_NUMBER, 7, '0') FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
    QUALIFY RN=1
)

-- InfoPro Core Account Data
, CTE_ARPCU AS (
    SELECT
        -- Primary Keys and Identifiers
        CUCO AS INFOPRO_DIVISION_NUMBER,
        CUCUNO AS ACCOUNT_NUMBER,
        CONCAT(CUCO, LPAD(CUCUNO, 7, '0')) AS CONCATENATED_ACCOUNT, -- TO USE JOIN WITH MDM ACCOUNT
        CUNAME,
        CUCATG,
        CUMACL,
        CUADR1,
        CUADR2,
        CUADR3,
        CUCITY,
        CUSTAT,
        CUPOST,
        CUCTRY,
        CUFAX,
        CUTEL,
        CORRECTED_ADDRESS_LINE_1,
        CORRECTED_ADDRESS_LINE_2,
        CORRECTED_ADDRESS_LINE_3,
        CORRECTED_CITY,
        CORRECTED_STATE,
        CORRECTED_COUNTY,
        CORRECTED_POSTAL_CODE,
        CORRECTED_POSTAL_SUFFIX,
        CORRECTED_COUNTRY_CODE,
        CORRECTED_COUNTRY_NAME,
        CORRECTED_COMPLETEADDRESS_MD5,
        CORRECTED_TELEPHONE_NUMBER,
        CORRECTED_FAX_NUMBER,
        OPERATION_TYPE,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_ARPCU,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_ARPCU,
        ODS_IFP_ARPCU_PK
    FROM {{ ref('ODS_IFP_ARPCU') }}
    {% if is_incremental() %}
        WHERE (CUCO, CUCUNO) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)

-- Billing Information
  , CTE_BIPCU AS (
    SELECT
        CUCOMP AS INFOPRO_DIVISION_NUMBER,
        CUACCT AS ACCOUNT_NUMBER,
        CUSTSP,
        CUAMFG,
        CUCTFG,
        CUINGP,
        CUEDSP,
        CUINV1,
        CUEXT,
        CUCROF,
        CUSUSD,
        CUSUSF,
        CUINV2,
        CUAQSN,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPCU,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPCU,
        ODS_IFP_BIPCU_PK
    FROM {{ ref('ODS_IFP_BIPCU') }}
    {% if is_incremental() %}
        WHERE (CUCOMP, CUACCT) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)


-- Fee Information
  , CTE_BIPIF AS (
    SELECT
        IFCOMP AS INFOPRO_DIVISION_NUMBER,
        IFACCT AS ACCOUNT_NUMBER,
        IFIFEE,
        IFBROK,
        IFDAT1,
        IFSFEE,
        IFLFEE,
        IFIEXC,
        IFLEXC,
        IFSEXC,
        IFFLG2,
        IFEFEE,
        IFFEXC,
        IFEEXC,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPIF,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPIF,
        ODS_IFP_BIPIF_PK
        
    FROM {{ ref('ODS_IFP_BIPIF') }}
    {% if is_incremental() %}
        WHERE (IFCOMP, IFACCT) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)

-- Credit Information
    , CTE_ARPCC AS (
        SELECT
                CCCO AS INFOPRO_DIVISION_NUMBER,
                CCCUNO AS ACCOUNT_NUMBER,
                CCRISK,
                CCDUNS,
                CCCRPC,
                CCCRDM,
                CCRVPC,
                CCDLCC,
                CCACD8,
                ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_ARPCC,
                ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_ARPCC,
                ODS_IFP_ARPCC_PK

        FROM {{ ref('ODS_IFP_ARPCC') }}
        {% if is_incremental() %}
            WHERE (CCCO, CCCUNO) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
        {% endif %}
    )

-- Additional InfoPro Tables for Complete Logic
, CTE_CDPARTB AS (
    SELECT
        Company AS INFOPRO_DIVISION_NUMBER,
        Account AS ACCOUNT_NUMBER,
        Quick_Pay_Enrollment_Type,
        Quick_Pay_Enr,
        INVOICE1_NUMBER,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CDPARTB,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CDPARTB,
        ODS_IFP_CDPARTB_PK

    FROM {{ ref('ODS_IFP_CDPARTB') }}
    {% if is_incremental() %}
        WHERE (Company, Account) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)

, CTE_CUPCST01 AS (
    SELECT
        CST_COMP AS INFOPRO_DIVISION_NUMBER,
        CST_ACCT AS ACCOUNT_NUMBER,
        CST_EMH1,
        CST_CNTR,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPCST01,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPCST01,
        ODS_IFP_CUPCST01_PK
        
    FROM {{ ref('ODS_IFP_CUPCST01') }}
    {% if is_incremental() %}
        WHERE (CST_COMP, CST_ACCT) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)

, CTE_BIPIFE AS (
    SELECT
        FECOMP AS INFOPRO_DIVISION_NUMBER,
        FEACCT AS ACCOUNT_NUMBER,
        FEAFLG,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPIFE,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPIFE,
        ODS_IFP_BIPIFE_PK
        
    FROM {{ ref('ODS_IFP_BIPIFE') }}
    {% if is_incremental() %}
        WHERE (FECOMP, FEACCT) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)

, CTE_ARPCR AS (
    SELECT
        CRCRPC,
        CRCLIM,
        ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_ARPCR,
        ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_ARPCR,
        ODS_IFP_ARPCR_PK
    FROM {{ ref('ODS_IFP_ARPCR') }}
    {% if is_incremental() %}
        WHERE CRCRPC IN (
            SELECT CCCRPC FROM {{ ref('ODS_IFP_ARPCC') }}
            WHERE (CCCO, CCCUNO) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
        )
    {% endif %}
)

, CTE_BIPAS AS (
    SELECT DISTINCT 
        ASCOMP AS INFOPRO_DIVISION_NUMBER,
        ASACCT AS ACCOUNT_NUMBER,
        'LACF' AS SALES_TERRITORY
    FROM {{ ref('ODS_IFP_BIPAS') }} BIPAS
    WHERE BIPAS.ASCOMP = '902' 
        AND BIPAS.ASTERR IN ('150','151') AND SRC_DEL_IND='N'
    {% if is_incremental() %}
        AND (BIPAS.ASCOMP, BIPAS.ASACCT) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)

-- Account Group Information
, CTE_CUPCUG_CUPCUA AS (
    SELECT
        CUPCUA.UACONO AS INFOPRO_DIVISION_NUMBER,
        CUPCUA.UAACCT AS ACCOUNT_NUMBER,
        CUPCUG.UGREQCSTID,
        CUPCUG.UGNAFLAG,
        CUPCUA.UAPARID,
        CUPCUA.UACOFAP,
        CUPCUG.UGACGPCD,
        CUPCUG.UGACGDS,
        CUPCUG.ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPCUG,
        CUPCUG.ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPCUG,
        CUPCUA.ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPCUA,
        CUPCUA.ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPCUA,
        CUPCUA.ODS_IFP_CUPCUA_PK,
        CUPCUG.ODS_IFP_CUPCUG_PK
    FROM {{ ref('ODS_IFP_CUPCUA') }} CUPCUA
    LEFT JOIN {{ ref('ODS_IFP_CUPCUG') }} CUPCUG
        ON CUPCUG.UGACGRPID = CUPCUA.UAACGRPID
    {% if is_incremental() %}
        WHERE (CUPCUA.UACONO, CUPCUA.UAACCT) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
)
, CTE_CONTAINER_CDM AS (
        SELECT
            ACCOUNT_NUMBER,
            INFOPRO_DIVISION_NUMBER,
            MIN(ORIGINAL_START_DATE) AS ORIGINAL_START_DATE,
            MAX(CLOSE_DATE) AS CLOSE_DATE,
            MAX(IS_ACTIVE) AS IS_ACTIVE,
            MAX(FRANCHISE_FLAG) AS FRANCHISE_FLAG
    FROM   {{ ref('CONTAINER') }}
    {% if is_incremental() %}
        WHERE (INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER) IN (SELECT INFOPRO_DIVISION_NUMBER, ACCOUNT_NUMBER FROM CTE_CHANGED_ACCOUNTS)
    {% endif %}
    GROUP BY ACCOUNT_NUMBER, INFOPRO_DIVISION_NUMBER
)

, CTE_TRANSFORMATION_ACCOUNT AS (

        SELECT
        ------------------- ARPCU INFO------------------------------
        ARPCU.INFOPRO_DIVISION_NUMBER,
        ARPCU.ACCOUNT_NUMBER,
        CONCAT(TRIM(ARPCU.INFOPRO_DIVISION_NUMBER), '-', TRIM(ARPCU.ACCOUNT_NUMBER)) AS ACCOUNT_COMPOSITE_KEY,
        ARPCU.CUNAME AS ACCOUNT_NAME,
        CASE 
            WHEN ARPCU.CUCATG = 'IND' THEN 'Industrial'
            WHEN ARPCU.CUCATG = 'COMM' THEN 'Commercial'
            WHEN ARPCU.CUCATG = 'PT' THEN 'Potables'
            WHEN ARPCU.CUCATG = 'RESI' THEN 'Residential'
            WHEN ARPCU.CUCATG = 'CNTRT' THEN 'Contract'
            WHEN ARPCU.CUCATG = '' THEN 'Category Not Specified'
            ELSE ARPCU.CUCATG 
        END AS ACCOUNT_CATEGORY,
        SUBSTR(TRIM(ARPCU.CUMACL), 1, 1) AS ACCOUNT_MAJOR_CLASS_CODE,
        CONCAT(COALESCE(ARPCU.CUADR1, ''), ' ', COALESCE(ARPCU.CUADR2, '')) AS BILLING_ADDRESS_LINE_1,
        ARPCU.CUADR3 AS BILLING_ADDRESS_LINE_2,
        ARPCU.CUCITY AS BILLING_CITY,
        ARPCU.CUSTAT AS BILLING_STATE,
        SUBSTRING(ARPCU.CUPOST, 1, 5) AS BILLING_POSTAL_CODE,
        CASE WHEN LENGTH(ARPCU.CUPOST) > 9 THEN SUBSTR(ARPCU.CUPOST, -4, 4) ELSE '' END AS BILLING_POSTAL_SUFFIX,
        ARPCU.CUCTRY AS BILLING_COUNTRY_CODE,
        MD5(CONCAT(COALESCE(ARPCU.CUADR1, ''), COALESCE(ARPCU.CUCITY, ''), COALESCE(ARPCU.CUSTAT, ''), COALESCE(SUBSTRING(ARPCU.CUPOST, 1, 5), ''))) AS BILLING_HASH_CODE,
        CASE WHEN ARPCU.CUFAX = '( ) -' OR SUBSTR(ARPCU.CUFAX, 1, 3) = '(  ' THEN '' ELSE ARPCU.CUFAX END AS BILLING_FAX,
        CASE WHEN ARPCU.CUTEL = '( ) -' OR SUBSTR(ARPCU.CUTEL, 1, 2) = '(0' THEN '' ELSE ARPCU.CUTEL END AS BILLING_PHONE,
        ARPCU.CORRECTED_ADDRESS_LINE_1,
        ARPCU.CORRECTED_ADDRESS_LINE_2,
        ARPCU.CORRECTED_ADDRESS_LINE_3,
        ARPCU.CORRECTED_CITY,
        ARPCU.CORRECTED_STATE,
        ARPCU.CORRECTED_COUNTY,
        ARPCU.CORRECTED_POSTAL_CODE,
        ARPCU.CORRECTED_POSTAL_SUFFIX,
        ARPCU.CORRECTED_COUNTRY_CODE,
        ARPCU.CORRECTED_COUNTRY_NAME,
        ARPCU.CORRECTED_COMPLETEADDRESS_MD5,
        ARPCU.CORRECTED_TELEPHONE_NUMBER,
        ARPCU.CORRECTED_FAX_NUMBER,
        ARPCU.INSERT_TIMESTAMP_ARPCU,
        ARPCU.UPDATE_TIMESTAMP_ARPCU,
        ARPCU.ODS_IFP_ARPCU_PK,

        ------------------ BIPCU INFO --------------------------

        CASE WHEN BIPCU.CUAMFG = 'P' THEN 'Y' ELSE 'N' END AS IS_PAPERLESS_INVOICE,
        CASE BIPCU.CUAMFG 
                WHEN 'A' THEN 'AUTOMATIC' 
                WHEN 'M' THEN 'MANUAL' 
                WHEN 'P' THEN 'PAPERLESS' 
                WHEN 'Z' THEN 'IMAGE' 
                ELSE 'UNKNOWN' 
        END AS INVOICE_PRINT_METHOD,
        CASE WHEN COALESCE(NULLIF(BIPCU.CUCTFG,''),'0') = '1' THEN 'Y' ELSE 'N' END AS IS_SUMMARY_BILLED,
        BIPCU.CUINGP AS INVOICE_GROUP_CODE,
        CASE WHEN BIPCU.CUSTSP IN ('4000-12-31','1700-01-01') THEN NULL ELSE BIPCU.CUSTSP END AS SUSPENSION_EFFECTIVE_START_DATE,
        CASE WHEN BIPCU.CUEDSP IN ('4000-12-31','1700-01-01')  THEN NULL  ELSE BIPCU.CUEDSP END AS SUSPENSION_EFFECTIVE_END_DATE,
        CASE WHEN COALESCE(BIPCU.CUINV1, '') IN ('Y', 'C') THEN 1 ELSE 0 END AS IS_CBS,
        CASE WHEN COALESCE(BIPCU.CUEXT, 0) = 0 THEN '' ELSE TO_CHAR(BIPCU.CUEXT) END AS BILLING_PHONE_EXTENSION,
        BIPCU.CUCROF AS ATTENTION,
        CASE WHEN BIPCU.CUSUSD NOT IN ('', 'N') THEN 'Y' ELSE 'N' END AS IS_SERVICE_INTERRUPT,
        CASE WHEN BIPCU.CUSUSD IN ('Y', 'M') THEN 'Y' ELSE 'N' END AS IS_SUSPENDED,
        CASE WHEN BIPCU.CUSUSF = 'Y' THEN 'Y' ELSE 'N' END AS IS_SERVICE_INTERRUPT_ELIGIBLE,
        BIPCU.CUINV2 AS IS_PRIORITY_CUSTOMER,
        BIPCU.CUAQSN AS ACQUISITION_CODE,
        BIPCU.INSERT_TIMESTAMP_BIPCU,
        BIPCU.UPDATE_TIMESTAMP_BIPCU,
        BIPCU.ODS_IFP_BIPCU_PK,


        ------------ BIPIF INFO ----------------------------------------------

        CASE WHEN BIPIF.IFDAT1 IN ('4000-12-31', '1700-01-01') THEN NULL ELSE BIPIF.IFDAT1 END AS NEXT_REVIEW_DATE,
        BIPIF.IFEEXC AS  ENVIRONMENTAL_FEE_EXEMPT_REASON,
        CASE WHEN COALESCE(LENGTH(BIPIF.IFBROK), 0) = 0 THEN 'No Broker' ELSE BIPIF.IFBROK END AS BROKER_CODE,
        BIPIF.IFIEXC AS ADMINISTRATIVE_FEE_EXEMPT_REASON, 
        BIPIF.IFSEXC AS  SERVICE_INTERRUPT_FEE_EXEMPT_REASON,
        BIPIF.IFLEXC AS LATE_PAYFEE_EXEMPT_REASON,
        BIPIF.IFFEXC AS FUEL_FEE_EXEMPT_REASON,
        CASE WHEN BIPIF.IFIFEE='Y' THEN 'Y' ELSE 'N' END as CHARGE_ADMINISTRATIVE_FEE_INDICATOR,
        CASE WHEN BIPIF.IFSFEE='Y' THEN 'Y' ELSE 'N' END AS CHARGE_SERVICE_INTERRUPT_FEE_INDICATOR,
        CASE WHEN bipif.IFLFEE='Y' THEN 'Y' ELSE 'N' END AS CHARGE_LATEPAY_FEE_INDICATOR,
        CASE WHEN bipif.IFFLG2='Y' THEN 'Y' ELSE 'N' END AS CHARGE_FUEL_FEE_INDICATOR,
        CASE WHEN bipif.IFEFEE='Y' THEN 'Y' ELSE 'N' END AS CHARGE_ENVIRONMENTAL_FEE_INDICATOR,
        CASE WHEN COALESCE(bipif.IFBROK, '') = '' THEN 'N' ELSE 'Y' END AS IS_BROKER,
        CASE 
            WHEN COALESCE(LENGTH(BIPIF.IFBROK), 0) = 0 THEN 'No Broker' 
            ELSE BIPIF.IFBROK 
        END AS BROKER_NAME,
        BIPIF.INSERT_TIMESTAMP_BIPIF,
        BIPIF.UPDATE_TIMESTAMP_BIPIF,
        BIPIF.ODS_IFP_BIPIF_PK,


        ---------------- ARPCC INFO ---------------------------------------------

        ARPCC.CCRISK AS CREDIT_RISK,
        ARPCC.CCCRDM AS CREDIT_ANALYST,
        ARPCC.CCDLCC AS DUNNING_STAGE,
        ARPCC.CCRVPC AS OPERATIONAL_RISK,
        CASE WHEN ARPCC.CCACD8>= CURRENT_TIMESTAMP() THEN 'OPEN' ELSE 'CLOSED' END AS ACCOUNT_STATUS,
        ARPCC.INSERT_TIMESTAMP_ARPCC,
        ARPCC.UPDATE_TIMESTAMP_ARPCC,
        ARPCC.ODS_IFP_ARPCC_PK,


        -------------- CDPARTB INFO ---------------------------------

        CASE WHEN CDPARTB.Quick_Pay_Enrollment_Type = 'R' THEN 'Y' ELSE 'N' END AS IS_AUTO_PAY,
        CASE WHEN CDPARTB.Quick_Pay_Enr = 'Y' THEN 'Y' ELSE 'N' END AS IS_ONLINE_BILL_PAY,
        CASE WHEN COALESCE(cdpartb.INVOICE1_NUMBER,'') <> '' THEN 'Y' ELSE 'N' END AS IS_INVOICED,
        CDPARTB.INSERT_TIMESTAMP_CDPARTB,
        CDPARTB.UPDATE_TIMESTAMP_CDPARTB,
        CDPARTB.ODS_IFP_CDPARTB_PK,


        ------------ CUPCST01 INFO ------------------------------------

        CUPCST01.CST_EMH1 AS BILLING_EMAIL,
        CUPCST01.INSERT_TIMESTAMP_CUPCST01,
        CUPCST01.UPDATE_TIMESTAMP_CUPCST01,
        CUPCST01.ODS_IFP_CUPCST01_PK,


        -----------------BIPIFE INFO -----------------------------------
        CASE WHEN BIPIFE.FEAFLG IN ('F','B','Y') THEN 'Y' ELSE 'N' END AS ADMIN_FEE_ON_FUEL_FEE_INDICATOR,
        CASE WHEN BIPIFE.FEAFLG IN ('E','B','Y') THEN 'Y' ELSE 'N' END AS ADMIN_FEE_ON_ENVIRONMENTAL_FEE_INDICATOR,
        BIPIFE.INSERT_TIMESTAMP_BIPIFE,
        BIPIFE.UPDATE_TIMESTAMP_BIPIFE,
        BIPIFE.ODS_IFP_BIPIFE_PK,

        -----------------ARPCR INFO -----------------------------------
        ARPCR.CRCLIM AS CREDIT_LIMIT,
        ARPCR.INSERT_TIMESTAMP_ARPCR,
        ARPCR.UPDATE_TIMESTAMP_ARPCR,
        ARPCR.ODS_IFP_ARPCR_PK,

        -----------------BIPAS INFO-----------------------------------

        BIPAS.SALES_TERRITORY,

        ----------------- CUPCUA INFO --------------------------------

        CUPCUG_CUPCUA.UAPARID AS CUSTOMER_MSA_NUMBER,
        CASE 
            WHEN CUPCUG_CUPCUA.UACOFAP IN (
                SELECT MARKET_SUB_VERTICAL_CODE
                FROM ETL_PROFITABILITY_XREF
                WHERE UPPER(MARKET_SUB_VERTICAL_DESCRIPTION) = 'MANUFACTURING'
            ) THEN 1
            ELSE 0
        END AS IS_MANUFACTURING,
        CUPCUG_CUPCUA.INSERT_TIMESTAMP_CUPCUA,
        CUPCUG_CUPCUA.UPDATE_TIMESTAMP_CUPCUA,
        CUPCUG_CUPCUA.ODS_IFP_CUPCUA_PK,

        ---------------- CUPCUG AND CUPCUA JOIN INFO ------------------------

        CASE WHEN CUPCUG_CUPCUA.UGREQCSTID = 'N' THEN 'Y' ELSE 'N' END AS IS_CENTRALLY_BILLED,
        CUPCUG_CUPCUA.UGACGDS AS ACCOUNT_CLASSIFICATION,
        COALESCE(CUPCUG_CUPCUA.UGNAFLAG,'N') AS IS_NATIONAL_ACCOUNT , 
        CUPCUG_CUPCUA.UGACGPCD AS ACCOUNT_GROUP,
        CUPCUG_CUPCUA.INSERT_TIMESTAMP_CUPCUG,
        CUPCUG_CUPCUA.UPDATE_TIMESTAMP_CUPCUG,
        CUPCUG_CUPCUA.ODS_IFP_CUPCUG_PK,

        -------------------- CONTAINER_CDM -------------------------

        CONTAINER_CDM.IS_ACTIVE AS IS_ACTIVE,
        COALESCE(CONTAINER_CDM.ORIGINAL_START_DATE, TO_DATE('1900-01-01')) AS ACCOUNT_OPEN_DATE,
        COALESCE(CONTAINER_CDM.CLOSE_DATE, TO_DATE('4000-01-01')) AS ACCOUNT_CLOSE_DATE,
        NULL AS FRANCHISE_FLAG,


        -------------------SFDC INFO --------------------------

        CASE WHEN SFDC.MY_RESOURCE_CUSTOMER__C = 1 THEN 'Y' ELSE 'N' END AS IS_MY_RESOURCE_CUSTOMER,
        SFDC.MY_RESOURCE_ENROLLMENT_DATE__C  AS MY_RESOURCE_ENROLL_DATE,
        SFDC.INSERT_TIMESTAMP_SFDC_ACCT,
        SFDC.UPDATE_TIMESTAMP_SFDC_ACCT,
        SFDC.ODS_SFDC_ACCOUNT_PK,

        -------------------- MDM ACCOUNT ------------------------

        -- MDM_ACCOUNT.CUSTOMER_NUMBER,
        -- MDM_ACCOUNT.DUNS_NUMBER,
        -- MDM_ACCOUNT.ACCOUNT_NAICS_CODE AS NAICS_CODE,
        -- MDM_ACCOUNT.CBS_NUMBER,
        -- MDM_ACCOUNT.CDH_CUSTOMER_ID AS CUSTOMER_ID,
        -- MDM_ACCOUNT.INSERT_TIMESTAMP_MDM_ACCOUNT,
        -- MDM_ACCOUNT.UPDATE_TIMESTAMP_MDM_ACCOUNT,
        -- MDM_ACCOUNT.ODS_MDM_ACCOUNT_PK,
        NULL AS CUSTOMER_NUMBER,
        NULL AS DUNS_NUMBER,
        NULL AS NAICS_CODE,
        NULL AS CBS_NUMBER,
        NULL AS CUSTOMER_ID,
        NULL AS INSERT_TIMESTAMP_MDM_ACCOUNT,
        NULL AS UPDATE_TIMESTAMP_MDM_ACCOUNT,
        NULL AS ODS_MDM_ACCOUNT_PK,


        NULL AS STRATEGIC_ORGANIZATION_ID, 
        NULL AS STRATEGIC_ORGANIZATION_NAME,
        NULL AS MARKET_VERTICAL_INDICATOR, 
        NULL AS REVENUE_DISTRIBUTION_CODE,  

        -------------- AUDIT COLUMNS ---------------------------

        'IFP,SFDC,MDM' AS SOURCE_SYSTEM,
        'ODS_IFP_ARPCU,ODS_IFP_BIPCU,ODS_IFP_BIPIF,ODS_IFP_CUPCUA,ODS_IFP_CUPCUG,ODS_IFP_ARPCC,ODS_IFP_CDPARTB,ODS_IFP_CUPCST01,ODS_IFP_BIPIFE,ODS_IFP_ARPCR,ODS_IFP_BIPAS,ODS_SFDC_ACCOUNT,ODS_MDM_ACCOUNT' AS SOURCE_TABLES,
        ARPCU.OPERATION_TYPE AS OPERATION_TYPE,
        'ARPCU' AS PRIMARY_DATA_SOURCE,
        NULL AS DQ_SCORE,
        'VALID' AS DQ_STATUS,
        NULL AS DQ_ERROR_CODE,
        NULL AS DQ_ERROR_MESSAGE,
        NULL AS DQ_VALIDATED_DATE

    FROM CTE_ARPCU ARPCU

    LEFT JOIN CTE_CONTAINER_CDM CONTAINER_CDM
            ON ARPCU.INFOPRO_DIVISION_NUMBER = CONTAINER_CDM.INFOPRO_DIVISION_NUMBER
            AND ARPCU.ACCOUNT_NUMBER = CONTAINER_CDM.ACCOUNT_NUMBER

    LEFT JOIN CTE_BIPCU BIPCU
        ON ARPCU.INFOPRO_DIVISION_NUMBER = BIPCU.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = BIPCU.ACCOUNT_NUMBER

    LEFT JOIN CTE_BIPIF BIPIF
        ON ARPCU.INFOPRO_DIVISION_NUMBER = BIPIF.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = BIPIF.ACCOUNT_NUMBER

    LEFT JOIN CTE_ARPCC ARPCC
        ON ARPCU.INFOPRO_DIVISION_NUMBER = ARPCC.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = ARPCC.ACCOUNT_NUMBER

    LEFT JOIN CTE_CDPARTB CDPARTB
        ON ARPCU.INFOPRO_DIVISION_NUMBER = CDPARTB.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = CDPARTB.ACCOUNT_NUMBER

    LEFT JOIN CTE_CUPCUG_CUPCUA CUPCUG_CUPCUA
        ON ARPCU.INFOPRO_DIVISION_NUMBER = CUPCUG_CUPCUA.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = CUPCUG_CUPCUA.ACCOUNT_NUMBER

    LEFT JOIN CTE_CUPCST01 CUPCST01
        ON ARPCU.INFOPRO_DIVISION_NUMBER = CUPCST01.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = CUPCST01.ACCOUNT_NUMBER
        AND CUPCST01.CST_CNTR = ''

    LEFT JOIN CTE_BIPIFE BIPIFE
        ON ARPCU.INFOPRO_DIVISION_NUMBER = BIPIFE.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = BIPIFE.ACCOUNT_NUMBER

    LEFT JOIN CTE_ARPCR ARPCR
        ON ARPCC.CCCRPC = ARPCR.CRCRPC

    LEFT JOIN CTE_BIPAS BIPAS
        ON ARPCU.INFOPRO_DIVISION_NUMBER = BIPAS.INFOPRO_DIVISION_NUMBER
        AND ARPCU.ACCOUNT_NUMBER = BIPAS.ACCOUNT_NUMBER
        
    LEFT JOIN CTE_SFDC SFDC
        ON ARPCU.INFOPRO_DIVISION_NUMBER = SFDC.INFOPRO_NUMBER__C
        AND LPAD(ARPCU.ACCOUNT_NUMBER, 7, '0') = LPAD(TRIM(SPLIT_PART(SFDC.INFOPRO_ACCOUNT_NUMBER__C, '/',2)), 7, '0')
    
    -- LEFT JOIN CTE_MDM_ACCOUNT MDM_ACCOUNT
    --     ON ARPCU.CONCATENATED_ACCOUNT = MDM_ACCOUNT.ACCOUNT_NUMBER

    -- Note: Incremental filtering is now done BEFORE the join via CTE_CHANGED_ACCOUNTS
    -- Each CTE is pre-filtered to only changed accounts, eliminating full table scans

)


SELECT
    -- Primary Keys and Composite Keys
    {{ generate_surrogate_key(['INFOPRO_DIVISION_NUMBER','ACCOUNT_NUMBER']) }} AS CDM_ACCOUNT_PK,
    CAST(ACCOUNT_COMPOSITE_KEY AS VARCHAR(15)) AS ACCOUNT_COMPOSITE_KEY,
    CAST(INFOPRO_DIVISION_NUMBER AS VARCHAR(5)) AS INFOPRO_DIVISION_NUMBER,
    CAST(ACCOUNT_NUMBER AS VARCHAR(14)) AS ACCOUNT_NUMBER,
    
    -- Account Core Information
    CAST(ACCOUNT_NAME AS VARCHAR(30)) AS ACCOUNT_NAME,
    CAST(ACCOUNT_CATEGORY AS VARCHAR(22)) AS ACCOUNT_CATEGORY,
    CAST(ACCOUNT_STATUS AS VARCHAR(10)) AS ACCOUNT_STATUS,
    CAST(IS_ACTIVE AS INT) AS IS_ACTIVE,
    
    -- Billing Address Information
    CAST(BILLING_HASH_CODE AS VARCHAR(32)) AS BILLING_HASH_CODE,
    CAST(BILLING_ADDRESS_LINE_1 AS VARCHAR(128)) AS BILLING_ADDRESS_LINE_1,
    CAST(BILLING_ADDRESS_LINE_2 AS VARCHAR(128)) AS BILLING_ADDRESS_LINE_2,
    CAST(BILLING_CITY AS VARCHAR(50)) AS BILLING_CITY,
    CAST(BILLING_STATE AS VARCHAR(50)) AS BILLING_STATE,
    CAST(BILLING_POSTAL_CODE AS VARCHAR(10)) AS BILLING_POSTAL_CODE,
    CAST(BILLING_POSTAL_SUFFIX AS VARCHAR(4)) AS BILLING_POSTAL_SUFFIX,
    CAST(BILLING_COUNTRY_CODE AS VARCHAR(5)) AS BILLING_COUNTRY_CODE,
    CAST(ATTENTION AS VARCHAR(60)) AS ATTENTION,
    CAST(BILLING_PHONE AS VARCHAR(50)) AS BILLING_PHONE,
    CAST(BILLING_PHONE_EXTENSION AS VARCHAR) AS BILLING_PHONE_EXTENSION,
    CAST(BILLING_FAX AS VARCHAR(50)) AS BILLING_FAX,
    CAST(BILLING_EMAIL AS VARCHAR) AS BILLING_EMAIL,
    CAST(CORRECTED_ADDRESS_LINE_1 AS VARCHAR(128)) AS CORRECTED_ADDRESS_LINE_1,
    CAST(CORRECTED_ADDRESS_LINE_2 AS VARCHAR(128)) AS CORRECTED_ADDRESS_LINE_2,
    CAST(CORRECTED_ADDRESS_LINE_3 AS VARCHAR(128)) AS CORRECTED_ADDRESS_LINE_3,
    CAST(CORRECTED_CITY AS VARCHAR(50)) AS CORRECTED_CITY,
    CAST(CORRECTED_STATE AS VARCHAR(50)) AS CORRECTED_STATE,
    CAST(CORRECTED_COUNTY AS VARCHAR(50)) AS CORRECTED_COUNTY,
    CAST(CORRECTED_POSTAL_CODE AS VARCHAR(10)) AS CORRECTED_POSTAL_CODE,
    CAST(CORRECTED_POSTAL_SUFFIX AS VARCHAR(4)) AS CORRECTED_POSTAL_SUFFIX,
    CAST(CORRECTED_COUNTRY_CODE AS VARCHAR(5)) AS CORRECTED_COUNTRY_CODE,
    CAST(CORRECTED_COUNTRY_NAME AS VARCHAR(100)) AS CORRECTED_COUNTRY_NAME,
    CAST(CORRECTED_COMPLETEADDRESS_MD5 AS VARCHAR(32)) AS CORRECTED_COMPLETEADDRESS_MD5,
    CAST(CORRECTED_TELEPHONE_NUMBER AS VARCHAR(50)) AS CORRECTED_TELEPHONE_NUMBER,
    CAST(CORRECTED_FAX_NUMBER AS VARCHAR(50)) AS CORRECTED_FAX_NUMBER,

    -- Account Dates
    CAST(ACCOUNT_OPEN_DATE AS DATETIME) AS ACCOUNT_OPEN_DATE,
    CAST(ACCOUNT_CLOSE_DATE AS DATETIME) AS ACCOUNT_CLOSE_DATE,
    CAST(NEXT_REVIEW_DATE AS DATETIME) AS NEXT_REVIEW_DATE,
    CAST(SUSPENSION_EFFECTIVE_START_DATE AS DATE) AS SUSPENSION_EFFECTIVE_START_DATE,
    CAST(SUSPENSION_EFFECTIVE_END_DATE AS DATE) AS SUSPENSION_EFFECTIVE_END_DATE,

    -- Business Attributes
    CAST(ACCOUNT_MAJOR_CLASS_CODE AS CHAR(1)) AS ACCOUNT_MAJOR_CLASS_CODE,
    CAST(ACQUISITION_CODE AS VARCHAR) AS ACQUISITION_CODE,
    CAST(MARKET_VERTICAL_INDICATOR AS VARCHAR(2)) AS MARKET_VERTICAL_INDICATOR,
    CAST(REVENUE_DISTRIBUTION_CODE AS VARCHAR(2)) AS REVENUE_DISTRIBUTION_CODE,
    CAST(FRANCHISE_FLAG AS VARCHAR(2)) AS FRANCHISE_FLAG,

    -- Invoice and Billing Configuration
    CAST(IS_PAPERLESS_INVOICE AS CHAR(1)) AS IS_PAPERLESS_INVOICE,
    CAST(INVOICE_PRINT_METHOD AS VARCHAR(20)) AS INVOICE_PRINT_METHOD,
    CAST(IS_SUMMARY_BILLED AS CHAR(1)) AS IS_SUMMARY_BILLED,
    CAST(INVOICE_GROUP_CODE AS VARCHAR) AS INVOICE_GROUP_CODE,
    CAST(IS_INVOICED AS CHAR(1)) AS IS_INVOICED,

    -- Service Status Flags
    CAST(IS_SERVICE_INTERRUPT AS CHAR(1)) AS IS_SERVICE_INTERRUPT,
    CAST(IS_SUSPENDED AS CHAR(1)) AS IS_SUSPENDED,
    CAST(IS_SERVICE_INTERRUPT_ELIGIBLE AS CHAR(1)) AS IS_SERVICE_INTERRUPT_ELIGIBLE,
    CAST(IS_PRIORITY_CUSTOMER AS VARCHAR) AS IS_PRIORITY_CUSTOMER,

    -- Payment Configuration
    CAST(IS_AUTO_PAY AS CHAR(1)) AS IS_AUTO_PAY,
    CAST(IS_ONLINE_BILL_PAY AS CHAR(1)) AS IS_ONLINE_BILL_PAY,
    
    -- Credit and Collections
    CAST(CREDIT_LIMIT AS DECIMAL) AS CREDIT_LIMIT,
    CAST(CREDIT_RISK AS VARCHAR) AS CREDIT_RISK,
    CAST(CREDIT_ANALYST AS VARCHAR) AS CREDIT_ANALYST,
    CAST(DUNNING_STAGE AS VARCHAR) AS DUNNING_STAGE,
    CAST(OPERATIONAL_RISK AS VARCHAR) AS OPERATIONAL_RISK,

    -- Fee Configuration
    CAST(CHARGE_ADMINISTRATIVE_FEE_INDICATOR AS CHAR(1)) AS CHARGE_ADMINISTRATIVE_FEE_INDICATOR,
    CAST(ADMINISTRATIVE_FEE_EXEMPT_REASON AS VARCHAR) AS ADMINISTRATIVE_FEE_EXEMPT_REASON,
    CAST(CHARGE_SERVICE_INTERRUPT_FEE_INDICATOR AS CHAR(1)) AS CHARGE_SERVICE_INTERRUPT_FEE_INDICATOR,
    CAST(SERVICE_INTERRUPT_FEE_EXEMPT_REASON AS VARCHAR) AS SERVICE_INTERRUPT_FEE_EXEMPT_REASON,
    CAST(CHARGE_LATEPAY_FEE_INDICATOR AS CHAR(1)) AS CHARGE_LATEPAY_FEE_INDICATOR,
    CAST(LATE_PAYFEE_EXEMPT_REASON AS VARCHAR) AS LATE_PAYFEE_EXEMPT_REASON,
    CAST(CHARGE_FUEL_FEE_INDICATOR AS CHAR(1)) AS CHARGE_FUEL_FEE_INDICATOR,
    CAST(FUEL_FEE_EXEMPT_REASON AS VARCHAR) AS FUEL_FEE_EXEMPT_REASON,
    CAST(CHARGE_ENVIRONMENTAL_FEE_INDICATOR AS CHAR(1)) AS CHARGE_ENVIRONMENTAL_FEE_INDICATOR,
    CAST(ENVIRONMENTAL_FEE_EXEMPT_REASON AS VARCHAR) AS ENVIRONMENTAL_FEE_EXEMPT_REASON,
    CAST(ADMIN_FEE_ON_FUEL_FEE_INDICATOR AS CHAR(1)) AS ADMIN_FEE_ON_FUEL_FEE_INDICATOR,
    CAST(ADMIN_FEE_ON_ENVIRONMENTAL_FEE_INDICATOR AS CHAR(1)) AS ADMIN_FEE_ON_ENVIRONMENTAL_FEE_INDICATOR,

    -- Broker Information
    CAST(BROKER_CODE AS VARCHAR) AS BROKER_CODE,
    CAST(BROKER_NAME AS VARCHAR(20)) AS BROKER_NAME,
    CAST(IS_BROKER AS CHAR(1)) AS IS_BROKER,

    -- Account Management
    CAST(SALES_TERRITORY AS VARCHAR) AS SALES_TERRITORY,
    CAST(ACCOUNT_GROUP AS VARCHAR) AS ACCOUNT_GROUP,
    CAST(IS_CENTRALLY_BILLED AS CHAR(1)) AS IS_CENTRALLY_BILLED,
    CAST(IS_CBS AS INT) AS IS_CBS,
    CAST(CBS_NUMBER AS VARCHAR(14)) AS CBS_NUMBER,
    
    -- Customer Hierarchy
    CAST(CUSTOMER_ID AS INT) AS CUSTOMER_ID,
    CAST(CUSTOMER_NUMBER AS VARCHAR(32)) AS CUSTOMER_NUMBER,
    CAST(CUSTOMER_MSA_NUMBER AS INT) AS CUSTOMER_MSA_NUMBER,
    CAST(IS_NATIONAL_ACCOUNT AS CHAR(1)) AS IS_NATIONAL_ACCOUNT,
    CAST(ACCOUNT_CLASSIFICATION AS VARCHAR(200)) AS ACCOUNT_CLASSIFICATION,

    -- Customer Profile
    CAST(IS_MANUFACTURING AS INT) AS IS_MANUFACTURING,
    CAST(MY_RESOURCE_ENROLL_DATE AS DATE) AS MY_RESOURCE_ENROLL_DATE,
    CAST(IS_MY_RESOURCE_CUSTOMER AS CHAR(1)) AS IS_MY_RESOURCE_CUSTOMER,
    CAST(NAICS_CODE AS VARCHAR) AS NAICS_CODE,
    CAST(DUNS_NUMBER AS VARCHAR) AS DUNS_NUMBER,
    
    -- Strategic Organization
    CAST(STRATEGIC_ORGANIZATION_ID AS VARCHAR) AS STRATEGIC_ORGANIZATION_ID,
    CAST(STRATEGIC_ORGANIZATION_NAME AS VARCHAR) AS STRATEGIC_ORGANIZATION_NAME,
    
    -- System and Audit Columns
    COALESCE(SOURCE_SYSTEM, 'ETL') AS SOURCE_SYSTEM,  
    CAST(SOURCE_TABLES AS VARCHAR) AS SOURCE_TABLES,
    CAST(PRIMARY_DATA_SOURCE AS VARCHAR) AS PRIMARY_DATA_SOURCE,
    CAST(INSERT_TIMESTAMP_ARPCU AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_ARPCU, 
    CAST(UPDATE_TIMESTAMP_ARPCU AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_ARPCU, 
    CAST(INSERT_TIMESTAMP_BIPCU AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_BIPCU, 
    CAST(UPDATE_TIMESTAMP_BIPCU AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_BIPCU, 
    CAST(INSERT_TIMESTAMP_BIPIF AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_BIPIF, 
    CAST(UPDATE_TIMESTAMP_BIPIF AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_BIPIF, 
    CAST(INSERT_TIMESTAMP_ARPCC AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_ARPCC, 
    CAST(UPDATE_TIMESTAMP_ARPCC AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_ARPCC, 
    CAST(INSERT_TIMESTAMP_CDPARTB AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_CDPARTB, 
    CAST(UPDATE_TIMESTAMP_CDPARTB AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_CDPARTB, 
    CAST(INSERT_TIMESTAMP_CUPCST01 AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_CUPCST01, 
    CAST(UPDATE_TIMESTAMP_CUPCST01 AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_CUPCST01, 
    CAST(INSERT_TIMESTAMP_BIPIFE AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_BIPIFE, 
    CAST(UPDATE_TIMESTAMP_BIPIFE AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_BIPIFE, 
    CAST(INSERT_TIMESTAMP_ARPCR AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_ARPCR, 
    CAST(UPDATE_TIMESTAMP_ARPCR AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_ARPCR, 
    CAST(INSERT_TIMESTAMP_CUPCUG AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_CUPCUG, 
    CAST(UPDATE_TIMESTAMP_CUPCUG AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_CUPCUG, 
    CAST(INSERT_TIMESTAMP_CUPCUA AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_IFP_CUPCUA, 
    CAST(UPDATE_TIMESTAMP_CUPCUA AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_IFP_CUPCUA, 
    CAST(INSERT_TIMESTAMP_SFDC_ACCT AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_SFDC_ACCOUNT, 
    CAST(UPDATE_TIMESTAMP_SFDC_ACCT AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_SFDC_ACCOUNT, 
    CAST(INSERT_TIMESTAMP_MDM_ACCOUNT AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_MDM_ACCOUNT, 
    CAST(UPDATE_TIMESTAMP_MDM_ACCOUNT AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_MDM_ACCOUNT, 
    
    -- ODS Primary Keys
    CAST(ODS_IFP_ARPCU_PK AS VARCHAR(32)) AS ODS_IFP_ARPCU_PK,
    CAST(ODS_IFP_BIPCU_PK AS VARCHAR(32)) AS ODS_IFP_BIPCU_PK,
    CAST(ODS_IFP_BIPIF_PK AS VARCHAR(32)) AS ODS_IFP_BIPIF_PK,
    CAST(ODS_IFP_CUPCUA_PK AS VARCHAR(32)) AS ODS_IFP_CUPCUA_PK,
    CAST(ODS_IFP_ARPCC_PK AS VARCHAR(32)) AS ODS_IFP_ARPCC_PK,
    CAST(ODS_IFP_CDPARTB_PK AS VARCHAR(32)) AS ODS_IFP_CDPARTB_PK,
    CAST(ODS_IFP_CUPCST01_PK AS VARCHAR(32)) AS ODS_IFP_CUPCST01_PK,
    CAST(ODS_IFP_BIPIFE_PK AS VARCHAR(32)) AS ODS_IFP_BIPIFE_PK,
    CAST(ODS_IFP_ARPCR_PK AS VARCHAR(32)) AS ODS_IFP_ARPCR_PK,
    CAST(ODS_IFP_CUPCUG_PK AS VARCHAR(32)) AS ODS_IFP_CUPCUG_PK,
    CAST(ODS_SFDC_ACCOUNT_PK AS VARCHAR(32)) AS ODS_SFDC_ACCOUNT_PK,
    CAST(ODS_MDM_ACCOUNT_PK AS VARCHAR(32)) AS ODS_MDM_ACCOUNT_PK,
    
    -- Data Quality and Batch Tracking
    CAST(DQ_STATUS AS VARCHAR(20)) AS DQ_STATUS,
    CAST(DQ_ERROR_CODE AS VARCHAR(50)) AS DQ_ERROR_CODE,
    CAST(DQ_ERROR_MESSAGE AS VARCHAR(500)) AS DQ_ERROR_MESSAGE,
    CAST(BATCH_ID AS BIGINT) AS CDM_INS_BATCH_ID,
    CAST(BATCH_ID AS BIGINT) AS CDM_UPD_BATCH_ID,
    CAST(TIME_STAMP AS TIMESTAMP_NTZ(9)) AS CDM_INSERT_TIMESTAMP,
    CAST(TIME_STAMP AS TIMESTAMP_NTZ(9)) AS CDM_UPDATE_TIMESTAMP,
    
    -- Operation and Hash Values
    CAST(OPERATION_TYPE AS VARCHAR(10)) AS OPERATION_TYPE,
    {{ generate_hash_change(relation = this) }} AS HASH_CHANGE,
    {{ generate_hash_full(relation = this) }} AS HASH_FULL

FROM CTE_TRANSFORMATION_ACCOUNT
JOIN CTE_BATCH_ID ON 1=1