{{ config(
	materialized='incremental',
    unique_key='CDM_CONTAINER_PK',
    on_schema_change='append_new_columns',
    tags=["cdm","customer","scheduled-nightly","data-observe"]
)}}

WITH CTE_BATCH_ID as (
    select TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')) as BATCH_ID , CURRENT_TIMESTAMP AS TIME_STAMP
)

,CTE_BIPAC AS (
	SELECT
			ACCOMP, ACACCT, ACSITE, ACCTGR,
			ACREVD, ACCNID, ACTOTL, ACPLTH,
			ACCGRP, ACMFCT, ACGRID, ACCTTP,
			ACTYPE, ACRCFQ, ACAVRC, ACAVSV,
			ACRATT, ACSTCD, ACDIST, ACDBIL,
			ACSDBL, ACLFCD, ACLFPC, ACLRAT,
			ACADPC, ACADFT, ACADFP, ACCRCD,
			ACDTAC, ACSHFL, ACMINL, ACPOFG,
			ACRCPT, ACCNFL, ACENDT, ACORDT,
			ACSTDT, ACRMDT, ACRODT, ACDRDT,
			ACREDT, ACBTDT, ACSSDT, ACSEDT,
			ACRMRT, ACRMCT, ACSTRC, ACCTSZ,
			ACOCAL, ACPUNT, ACMOND, ACTUES,
			ACWEDN, ACTHUR, ACFRID, ACSATU,
			ACSUND, ACMORQ, ACTURQ, ACWERQ,
			ACTHRQ, ACFRRQ, ACSARQ, ACSURQ,
			ACQTYC, ACQTYS, ACOLDN, ACCPAC,
			ACCOWN, ACMUNP, ACFMT,
            OPERATION_TYPE,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPAC,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPAC,
			ODS_IFP_BIPAC_PK

		FROM {{ ref('ODS_IFP_BIPAC') }}
),


CTE_BIPACC AS (
	SELECT
			ODS_IFP_BIPACC_PK,
			ACCOMP, ACACCT, ACSITE, ACCTGR,
			ACAVGW, ACCITY, ACFG05, ACFG04,
			ACFG03, ACCOMM,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPACC,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPACC
	
		FROM {{ ref('ODS_IFP_BIPACC') }}
		
),

CTE_BIPCG AS (
	SELECT
			ODS_IFP_BIPCG_PK,
			CGCOMP, CGMFCT, CGCGRP, CGACCT,CGGNAM,
			CGSUMR, CGSVC1,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPCG,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPCG
		
		FROM {{ ref('ODS_IFP_BIPCG') }}
		
),

CTE_BIPCG_IND AS (
	SELECT
			ODS_IFP_BIPCG_PK,
			CGCOMP, CGMFCT, CGCGRP, CGACCT,
			CGINDA, CGINIR, CGCLDT, 
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPCG_IND,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPCG_IND
		
		FROM {{ ref('ODS_IFP_BIPCG') }}
		WHERE  CGCLDT > DATEADD(YEAR,-8,getdate())
),

CTE_BIPCM AS 
(
    SELECT
			CMCOMP,CMMFCT,
			CMACCT,CMCTTY,
			ODS_IFP_BIPCM_PK,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPCM,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPCM
		FROM {{ ref('ODS_IFP_BIPCM') }}
		
),

CTE_BIPTB AS (
    SELECT
			ODS_IFP_BIPTB_PK,
			TBDIVN,
			TBELEM,
			TBDESC,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_BIPTB,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_BIPTB,
			ROW_NUMBER() OVER(
				PARTITION BY TBDIVN, TBELEM
				ORDER BY ODS_UPDATE_TIMESTAMP DESC
			) AS BIPTB_RN
		FROM {{ ref('ODS_IFP_BIPTB') }}
		WHERE TBTBLN = 'CCT'
		QUALIFY BIPTB_RN = 1
),

CTE_CUPASSCODE AS (
            SELECT  
				ODS_IFP_CUPASSCODE_PK,
				ASCASCD,
				ASCCOMP,
				ASCASDS, 
				ASCTYPE,
				ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPASSCODE,
				ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPASSCODE,
				ROW_NUMBER() OVER(
					PARTITION BY ASCASCD
					ORDER BY ODS_UPDATE_TIMESTAMP DESC
				) AS CUPASSCODE_RN
			FROM {{ ref('ODS_IFP_CUPASSCODE') }}
			QUALIFY CUPASSCODE_RN = 1
),


CTE_CUPASSACCT AS (
    SELECT  ODS_IFP_CUPASSACCT_PK,
			ASACOMP, ASAACCT, 
			ASASITE, ASACTGR, 
			ASAASCD, ASAMFCT,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPASSACCT,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPASSACCT,
			ROW_NUMBER() OVER(
            PARTITION BY ASACOMP, ASAACCT, ASASITE, ASACTGR 
            ORDER BY ODS_UPDATE_TIMESTAMP DESC
        ) AS CUPASSACCT_RN	
		FROM {{ ref('ODS_IFP_CUPASSACCT') }}
		QUALIFY CUPASSACCT_RN = 1
		
),

CTE_CUPTB_RRQ AS (
	SELECT
			ODS_IFP_CUPTB_PK,
			TBELEM,
			TBDESC,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPTB,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPTB
	
		FROM {{ ref('ODS_IFP_CUPTB') }}
		WHERE TBTBLN = 'RRQ'
)

,CTE_CUPTB_MVT AS (
	SELECT
			TBELEM,
			TBDESC

		FROM {{ ref('ODS_IFP_CUPTB') }}
		WHERE TBTBLN = 'MVT'
)

,CTE_CUPTB_DGC AS (
	SELECT
			TBELEM,
			TBDESC,
			ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_CUPTB_DGC,
			ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_CUPTB_DGC
		FROM {{ ref('ODS_IFP_CUPTB') }}
		WHERE TBTBLN = 'DGC' 
)
, CTE_CUPTB_CCT AS (
	SELECT
			TBELEM,
			TBDESC
		FROM {{ ref('ODS_IFP_CUPTB') }}
		WHERE TBTBLN = 'CCT'
)

-- this logic is taken from Onprem mappings 
,CTE_CDH_ASSET AS (
	SELECT
		apsr_sfdc.PK_System_Relational_Key AS CONTAINER_SFDC_NUMBER,
        CASE WHEN ap.PK_AssetProfile_ID IS NULL THEN 0 ELSE ap.PK_AssetProfile_ID END AS ASSET_PROFILE_NUMBER,
		SUBSTRING(apsr_ifp.PK_System_Relational_Key,1,3) AS InfoproDiv,
		CAST(CAST(SUBSTRING(apsr_ifp.PK_System_Relational_Key,4,7) AS INTEGER) AS VARCHAR(14)) AS Acct_Nbr,
		SUBSTRING(apsr_ifp.PK_System_Relational_Key,11,5) AS Site_Nbr,
		SUBSTRING(apsr_ifp.PK_System_Relational_Key,16,2) AS CTGR_Nbr,
		ap.ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_ASSETPROFILE,
		apsr_ifp.ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_ASSET_SYS_REL_IFP,
		apsr_sfdc.ODS_INSERT_TIMESTAMP AS INSERT_TIMESTAMP_ASSET_SYS_REL_SFDC,
		ap.ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_ASSETPROFILE,	
		apsr_ifp.ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_ASSET_SYS_REL_IFP,
		apsr_sfdc.ODS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP_ASSET_SYS_REL_SFDC,
		ap.ODS_CDH_ASSETPROFILE_PK AS ODS_CDH_ASSETPROFILE_PK,
		apsr_ifp.ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP_PK AS ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP_PK,
		(SELECT ODS_CDH_SYSTEM_PK FROM {{ ref('ODS_CDH_SYSTEM') }} WHERE SYSTEM_NAME = 'Infopro' AND ACTIVE_RECORD_FLAG = 'Y'  LIMIT 1) AS ODS_CDH_SYSTEM_PK,
		(SELECT ODS_INSERT_TIMESTAMP FROM {{ ref('ODS_CDH_SYSTEM') }} WHERE SYSTEM_NAME = 'Infopro' AND ACTIVE_RECORD_FLAG = 'Y' LIMIT 1) AS INSERT_TIMESTAMP_SYSTEM,
        (SELECT ODS_UPDATE_TIMESTAMP FROM {{ ref('ODS_CDH_SYSTEM') }} WHERE SYSTEM_NAME = 'Infopro' AND ACTIVE_RECORD_FLAG = 'Y' LIMIT 1) AS UPDATE_TIMESTAMP_SYSTEM
	FROM {{ ref('ODS_CDH_ASSETPROFILE') }} ap
	LEFT JOIN {{ ref('ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP') }} apsr_ifp
		ON ap.PK_AssetProfile_ID = apsr_ifp.PK_AssetProfile_ID
		AND apsr_ifp.PK_SYSTEM_ID = (
			SELECT PK_SYSTEM_ID FROM {{ ref('ODS_CDH_SYSTEM') }} cdh_sys
			WHERE SYSTEM_NAME = 'Infopro' AND ACTIVE_RECORD_FLAG = 'Y' --AND CURRENT_IND = 'Y'
		)
		AND apsr_ifp.ACTIVE_RECORD_FLAG = 'Y'
		--AND apsr_ifp.CURRENT_IND = 'Y' , column CURRENT_IND is not exist
	LEFT JOIN {{ ref('ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP') }} apsr_sfdc
		ON ap.PK_AssetProfile_ID = apsr_sfdc.PK_AssetProfile_ID
		AND apsr_sfdc.PK_SYSTEM_ID = (
			SELECT PK_SYSTEM_ID
			FROM {{ ref('ODS_CDH_SYSTEM') }} 
			WHERE SYSTEM_NAME = 'Salesforce' AND ACTIVE_RECORD_FLAG = 'Y' --AND CURRENT_IND = 'Y'
		)
		AND apsr_sfdc.ACTIVE_RECORD_FLAG = 'Y'
		--AND apsr_sfdc.CURRENT_IND = 'Y'
	WHERE ap.ACTIVE_RECORD_FLAG = 'Y'
)

-- CORPORATE_HIERARCHY CTE for future integration
-- When CORPORATE_HIERARCHY model becomes available, uncomment below:
-- ,CTE_CORPORATE_HIERARCHY AS (
-- 	SELECT
-- 		INFOPRO_DIVISION_NUMBER,
-- 		REVENUE_DISTRIBUTION_CODE,
-- 		CORPORATE_HIERARCHY_COMPOSITE_KEY
-- 	FROM {{ '{{' }} ref('CORPORATE_HIERARCHY') {{ '}}' }}
-- )


,CTE_TRANSFORMATION_CONTAINER AS (
		
	SELECT	
    -------------------- BIPAC columns --------------------

	bipac.ACCOMP AS INFOPRO_DIVISION_NUMBER,
	bipac.ACACCT AS ACCOUNT_NUMBER,
	bipac.ACSITE AS SITE_NUMBER,
	bipac.ACCTGR AS CONTAINER_GROUP_NUMBER,
	bipac.ACREVD AS REVENUE_DISTRIBUTION_CODE,
	CONCAT(bipac.ACCOMP, '-', LPAD(bipac.ACACCT,7,'0'), '-', bipac.ACSITE, '-', LPAD(bipac.ACCTGR,2,'0')) AS CONTAINER_COMPOSITE_KEY,
	CONCAT(bipac.ACCOMP, '-', LPAD(bipac.ACACCT,7,'0'), '-', bipac.ACSITE) AS SITE_COMPOSITE_KEY,
	CONCAT(bipac.ACCOMP, '-', LPAD(bipac.ACACCT,7,'0')) AS ACCOUNT_COMPOSITE_KEY,
	CASE WHEN bipac.ACCNID IS NOT NULL AND TRIM(bipac.ACCNID) <> '' THEN 1 ELSE 0 END AS IS_SHARED,
    bipac.ACTOTL AS PICKUP_PERIOD_TOTAL_LIFTS,
    bipac.ACPLTH AS PICKUP_PERIOD_LENGTH,
	CASE 
		WHEN bipac.ACOCAL = 'Y' THEN 'OnCall' 
		WHEN bipac.ACTOTL = 0 OR bipac.ACPLTH = 0 THEN 'None' 
		WHEN bipac.ACPLTH = 52 THEN CAST(bipac.ACTOTL AS VARCHAR) || ' Per Year' 
		WHEN bipac.ACPLTH = 1 THEN CAST(bipac.ACTOTL AS VARCHAR) || ' Every Week' 
		WHEN bipac.ACPLTH = 4 THEN CAST(bipac.ACTOTL AS VARCHAR) || ' Per Month' 
		ELSE CAST(bipac.ACTOTL AS VARCHAR) || ' Every ' || CAST(bipac.ACPLTH AS VARCHAR) || ' Weeks' 
	END AS LIFT_SCHEDULE_DESCRIPTION,
	bipac.ACCGRP AS CONTRACT_GROUP_NUMBER,
	bipac.ACMFCT AS MUNICIPAL_FRANCHISE_CONTRACT,
	bipac.ACGRID AS GRID_NUMBER,
	CASE WHEN TRIM(ACTYPE) = '' THEN 'P' ELSE ACTYPE END AS ACCOUNT_TYPE,
	bipac.ACRCFQ AS RECURRING_CHARGE_FREQUENCY,
	bipac.ACAVRC AS RECURRING_MONTHS_ADV_BILL,
	bipac.ACAVSV AS SERVICE_MONTHS_ADV_BILL,
	bipac.ACRATT AS RATE_TYPE,
	bipac.ACSTCD AS STOP_CODE,
	bipac.ACDIST AS DISTRICT_CODE,
	CASE WHEN bipac.ACDBIL = 'Y' THEN 1 ELSE 0 END AS IS_DISPOSAL_BILLABLE,
	CASE WHEN bipac.ACSDBL = 'Y' THEN 1 ELSE 0 END AS IS_STD_DISPOSAL_BILLABLE,
	bipac.ACLFCD AS DISPOSAL_CODE,
	bipac.ACLFPC AS DISPOSAL_PRICE_CODE,
	CASE WHEN bipac.ACLRAT IS NULL THEN 0 ELSE bipac.ACLRAT END AS DISPOSAL_RATE_PER_UNIT,
	CASE WHEN bipac.ACADPC IS NULL THEN 0 ELSE bipac.ACADPC END AS DISPOSAL_ADJUSTMENT_VALUE,
	CASE WHEN bipac.ACADFT IS NULL THEN 0 ELSE bipac.ACADFT END AS DISPOSAL_DOLLAR_ADJUSTMENT,
	CASE WHEN bipac.ACADFP IS NULL THEN '0' ELSE bipac.ACADFP END AS DISPOSAL_ADJUSTMENT_CODE,
	CASE WHEN bipac.ACCRCD IS NULL THEN '0' ELSE bipac.ACCRCD END AS DISPOSAL_COST_PER_REVENUE_CODE,
	CASE WHEN bipac.ACDTAC IS NULL THEN '0' ELSE bipac.ACDTAC END AS DISPOSAL_TAX_APPLICATION_CODE,
	CASE
	  -- Step 1: Check special handling flag against lookup table
		WHEN bipac.ACSHFL IN ('#', '1', '6', 'E', 'F', 'M', 'N', 'U') THEN 'Solid Waste'  -- MSW
		WHEN bipac.ACSHFL IN ('!', '�', '0', '2', '3', '4', '7', '8', '9', 'B', 'C', 'G', 'I', 'J', 'K', 'L', 'O', 'P', 'Q', 'R', 'T', 'V', 'Y', 'Z') THEN 'Recycle'  -- REC
	  	WHEN bipac.ACSHFL IN ('%', '&', '*', '@', '5', 'W') THEN 'Other'  -- C&D/Other
	  	WHEN bipac.ACSHFL IN ('A', 'D', 'H', 'S', 'X') THEN 'Other'  -- IND/Other
	  -- Step 2: If ACSHFL is blank/null, check container type
	  	WHEN (bipac.ACSHFL IS NULL OR bipac.ACSHFL = ' ')
	    		AND bipac.ACCTTP IN ('RC', 'BB', 'RB', 'FC', 'FR', 'YC') THEN 'Recycle'  -- Recycle container types
	  	WHEN (bipac.ACSHFL IS NULL OR bipac.ACSHFL = ' ')
	    		AND bipac.ACCTTP = 'YC' THEN 'Yard Waste'  -- Yard waste container
	  	WHEN (bipac.ACSHFL IS NULL OR bipac.ACSHFL = ' ')
	    		AND bipac.ACCTTP = 'OC' THEN 'Organics'  -- Organics container
	  -- Step 3: If still no match, check revenue distribution code 2nd digit
	  	WHEN SUBSTRING(bipac.ACREVD, 2, 1) = '7' THEN 'Recycle'
	  	-- Default: Solid Waste
	  	ELSE 'Solid Waste'
	END AS WASTE_STREAM_DESCRIPTION,
	bipac.ACSHFL AS SPECIAL_HANDLING_CODE,
	CAST(CASE WHEN (CASE WHEN bipacc.ACFG04 IS NULL THEN '' ELSE bipacc.ACFG04 END) = 'F' THEN TRUE ELSE FALSE END AS VARCHAR) AS FRANCHISE_FLAG,
	CAST(CASE WHEN bipac.ACPOFG IS NULL THEN 0 WHEN bipac.ACPOFG = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_PURCHASE_ORDER_REQUIRED,
	CASE WHEN bipac.ACRCPT IS NULL THEN '' ELSE bipac.ACRCPT END AS RECEIPT_REQUIRED_CODE,
	CAST(CASE WHEN bipac.ACCNFL IS NULL THEN 0 WHEN bipac.ACCNFL = 'Y' THEN 1 ELSE 0 END AS INT) AS HAS_CONTAINER_NOTES,
	CAST(CASE WHEN bipac.ACENDT > CURRENT_DATE THEN 1 ELSE 0 END AS INT) AS IS_ACTIVE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACORDT)) AS DATETIME) AS ORIGINAL_START_DATE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACSTDT)) AS DATE) AS LAST_SERVICE_DATE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACRMDT)) AS DATE) AS REMOVAL_DATE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACENDT)) AS DATETIME) AS CLOSE_DATE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACRODT)) AS DATETIME) AS RATE_RESTRICTION_DATE,
	CASE WHEN bipac.ACDRDT<>'0' AND TRY_TO_DATE(TO_VARCHAR(bipac.ACDRDT)) IS NOT NULL THEN CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACDRDT)) AS DATE) ELSE CAST(TRY_TO_DATE('9999-12-31') AS DATE) END AS DISPOSAL_RATE_RESTRICTION_DATE,
	CAST(bipac.ACREDT AS DATE) AS NEXT_RECURRING_CHARGE_GENERATION_DATE,
	CAST(bipac.ACBTDT AS DATE) AS BILLED_TO_DATE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACSSDT)) AS DATETIME) AS SEASONAL_STOP_DATE,
	CAST(TRY_TO_DATE(TO_VARCHAR(bipac.ACSEDT)) AS DATETIME) AS SEASONAL_RESTART_DATE,
	CAST(CASE WHEN bipac.ACRMRT = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_SEASONAL_REMOVE_ROUTE,
	CAST(CASE WHEN bipac.ACRMCT = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_SEASONAL_REMOVE_CONTAINER,
	CAST(CASE WHEN bipac.ACSTRC = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_SEASONAL_RECURRING_CHARGE,
	bipac.ACCTTP AS CONTAINER_TYPE,
	bipac.ACCTSZ AS CONTAINER_SIZE,
	bipac.ACCNID AS SHARED_CONTAINER_ID,
	CASE WHEN bipac.ACPUNT = 'W' THEN 'WEEK' ELSE 'UNKNOWN' END AS PICKUP_PERIOD_UNIT,
	CASE WHEN bipac.ACPLTH = 1 THEN 'WEEKLY' WHEN bipac.ACPLTH = 2 THEN 'EOW' WHEN bipac.ACPLTH = 4 THEN 'MONTHLY' WHEN bipac.ACPLTH = 0 THEN 'ON CALL' ELSE 'OTHER' END AS PICKUP_SCHEDULE,
	CAST(bipac.ACMINL AS DECIMAL) AS MINIMUM_NUMBER_OF_LIFTS,
	CASE WHEN bipac.ACMOND IS NULL THEN 0 ELSE bipac.ACMOND END AS MONDAY_LIFT_DAY,
	CASE WHEN bipac.ACTUES IS NULL THEN 0 ELSE bipac.ACTUES END AS TUESDAY_LIFT_DAY,
	CASE WHEN bipac.ACWEDN IS NULL THEN 0 ELSE bipac.ACWEDN END AS WEDNESDAY_LIFT_DAY,
	CASE WHEN bipac.ACTHUR IS NULL THEN 0 ELSE bipac.ACTHUR END AS THURSDAY_LIFT_DAY,
	CASE WHEN bipac.ACFRID IS NULL THEN 0 ELSE bipac.ACFRID END AS FRIDAY_LIFT_DAY,
	CASE WHEN bipac.ACSATU IS NULL THEN 0 ELSE bipac.ACSATU END AS SATURDAY_LIFT_DAY,
	CASE WHEN bipac.ACSUND IS NULL THEN 0 ELSE bipac.ACSUND END AS SUNDAY_LIFT_DAY,
	CAST(CASE WHEN (CASE WHEN bipac.ACMORQ IS NULL THEN '' ELSE bipac.ACMORQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_MONDAY_REQUIRED,
	CAST(CASE WHEN (CASE WHEN bipac.ACTURQ IS NULL THEN '' ELSE bipac.ACTURQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_TUESDAY_REQUIRED,
	CAST(CASE WHEN (CASE WHEN bipac.ACWERQ IS NULL THEN '' ELSE bipac.ACWERQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_WEDNESDAY_REQUIRED,
	CAST(CASE WHEN (CASE WHEN bipac.ACTHRQ IS NULL THEN '' ELSE bipac.ACTHRQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_THURSDAY_REQUIRED,
	CAST(CASE WHEN (CASE WHEN bipac.ACFRRQ IS NULL THEN '' ELSE bipac.ACFRRQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_FRIDAY_REQUIRED,
	CAST(CASE WHEN (CASE WHEN bipac.ACSARQ IS NULL THEN '' ELSE bipac.ACSARQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_SATURDAY_REQUIRED,
	CAST(CASE WHEN (CASE WHEN bipac.ACSURQ IS NULL THEN '' ELSE bipac.ACSURQ END) = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_SUNDAY_REQUIRED,
	CASE WHEN bipac.ACQTYC IS NULL THEN 0 ELSE bipac.ACQTYC END AS CONTAINER_COUNT,
	CASE WHEN bipac.ACQTYS IS NULL THEN 0 ELSE bipac.ACQTYS END AS CONTAINER_QUANTITY_ON_SITE,
	CASE WHEN (CASE WHEN bipac.ACPLTH IS NULL THEN 0 ELSE bipac.ACPLTH END) = 0 THEN 0 ELSE (((bipac.ACTOTL / bipac.ACPLTH) * bipac.ACCTSZ) * 52) / 12 END AS YARDAGE,
	CASE WHEN bipac.ACOLDN IS NULL THEN '0' ELSE bipac.ACOLDN END AS UNIT_OF_MEASURE,
	CAST(CASE WHEN bipac.ACCPAC = 'C' THEN 1 ELSE 0 END AS INT) AS HAS_COMPACTOR,
	CAST(CASE WHEN bipac.ACCOWN = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_CONTAINER_OWNED,
	CAST(CASE WHEN bipac.ACOCAL = 'Y' THEN 1 ELSE 0 END AS INT) AS IS_ONCALL,
    CAST(CASE WHEN COALESCE(bipac.ACMUNP, '') = 'Y' THEN TRUE ELSE FALSE END AS VARCHAR) AS MUNICIPAL_FLAG,


    -------------------- BIPACC columns --------------------

	bipacc.ACAVGW AS EXCESS_TON_AMOUNT,
	CAST(bipacc.ACAVGW AS DECIMAL) AS AVERAGE_WEIGHT,
	bipacc.ACCITY AS CITY_ACCOUNT_NUMBER,
	CASE WHEN bipacc.ACFG05 IS NULL THEN '' ELSE bipacc.ACFG05 END AS MARKET_VERTICAL_INDICATOR,
	cuptb_mvt.TBDESC AS MARKET_DESCRIPTION,
    bipacc.ACFG03 AS REMOTE_MONITOR_FLAG,
    bipacc.ACCOMM AS COMMODITY_CODE,

    -------------------- BIPCG columns --------------------

    bipcg.CGGNAM AS MUNICIPAL_CONTRACT_GROUP_NAME,
    bipcg.CGSUMR AS SUMMARY_ROUTING_FLAG,
    bipcg_ind.CGINDA AS INDIVIDUAL_ACCOUNT_FLAG,
    bipcg_ind.CGINIR AS INDIVIDUAL_INVOICES_REQUIRED_FLAG,
	bipcg.CGSVC1 AS DIGITAL_COMMUNICATIONS_FLAG,

    -------------------- BIPCM columns --------------------

    bipcm.CMCTTY AS MUNICIPAL_CONTRACT_TYPE,

    -------------------- BIPTB columns --------------------

    biptb.TBDESC AS CONTAINER_NAME,

    -------------------- CUPASSACCT columns --------------------

    CAST(cupassacct.ASAASCD AS VARCHAR(255)) AS ASSOCIATION_CODE,

	-------------------- CUPASSCODE columns --------------------

	cupasscode.ASCASDS AS ASSOCIATION_DESC,
	cupasscode.ASCTYPE AS ASSOCIATION_TYPE,

	-------------------- CUPTB columns --------------------

	cuptb_rrq.TBDESC AS RECEIPT_REQUIRED_DESCRIPTION,
	cuptb_dgc.TBDESC AS DIGITAL_COMMUNICATIONS_CODE,
	CAST(cuptb_cct.TBDESC AS VARCHAR) AS PRODUCT_DESCRIPTION,

    -------------------- CDH_Asset columns -----------------------

    cdh_asset.ASSET_PROFILE_NUMBER AS ASSET_PROFILE_NUMBER,
    cdh_asset.CONTAINER_SFDC_NUMBER AS CONTAINER_SFDC_NUMBER,

	
	-------------------- CORPORATE_HIERARCHY columns --------------------

	-- corp_hier.CORPORATE_HIERARCHY_COMPOSITE_KEY AS CORPORATE_HIERARCHY_COMPOSITE_KEY,
	NULL AS CORPORATE_HIERARCHY_COMPOSITE_KEY, -- Placeholder until corporate hierarchy  is defined and integrated

	----------------------- Source timestamp columns----------------------- - BIPAC

	INSERT_TIMESTAMP_BIPAC AS INSERT_TIMESTAMP_ODS_IFP_BIPAC,
	UPDATE_TIMESTAMP_BIPAC AS UPDATE_TIMESTAMP_ODS_IFP_BIPAC,
	
	INSERT_TIMESTAMP_BIPACC AS INSERT_TIMESTAMP_ODS_IFP_BIPACC,
	UPDATE_TIMESTAMP_BIPACC AS UPDATE_TIMESTAMP_ODS_IFP_BIPACC,
	
	INSERT_TIMESTAMP_BIPCG AS INSERT_TIMESTAMP_ODS_IFP_BIPCG,
	UPDATE_TIMESTAMP_BIPCG AS UPDATE_TIMESTAMP_ODS_IFP_BIPCG,
	
	INSERT_TIMESTAMP_BIPCM AS INSERT_TIMESTAMP_ODS_IFP_BIPCM,
	UPDATE_TIMESTAMP_BIPCM AS UPDATE_TIMESTAMP_ODS_IFP_BIPCM,
	
	INSERT_TIMESTAMP_BIPTB AS INSERT_TIMESTAMP_ODS_IFP_BIPTB,
	UPDATE_TIMESTAMP_BIPTB AS UPDATE_TIMESTAMP_ODS_IFP_BIPTB,
	
	INSERT_TIMESTAMP_CUPASSACCT AS INSERT_TIMESTAMP_ODS_IFP_CUPASSACCT,
	UPDATE_TIMESTAMP_CUPASSACCT AS UPDATE_TIMESTAMP_ODS_IFP_CUPASSACCT,
	
	INSERT_TIMESTAMP_CUPASSCODE AS INSERT_TIMESTAMP_ODS_IFP_CUPASSCODE,
	UPDATE_TIMESTAMP_CUPASSCODE AS UPDATE_TIMESTAMP_ODS_IFP_CUPASSCODE,
	
	INSERT_TIMESTAMP_CUPTB AS INSERT_TIMESTAMP_ODS_IFP_CUPTB,
	UPDATE_TIMESTAMP_CUPTB AS UPDATE_TIMESTAMP_ODS_IFP_CUPTB,
	
	INSERT_TIMESTAMP_ASSETPROFILE AS INSERT_TIMESTAMP_ODS_CDH_ASSETPROFILE,
	UPDATE_TIMESTAMP_ASSETPROFILE AS UPDATE_TIMESTAMP_ODS_CDH_ASSETPROFILE,
	INSERT_TIMESTAMP_ASSET_SYS_REL_IFP AS INSERT_TIMESTAMP_ODS_CDH_ASSET_SYSTEM_RELATIONSHIP,
	UPDATE_TIMESTAMP_ASSET_SYS_REL_IFP AS UPDATE_TIMESTAMP_ODS_CDH_ASSET_SYSTEM_RELATIONSHIP,
	CAST(INSERT_TIMESTAMP_ASSET_SYS_REL_SFDC AS TIMESTAMP_NTZ(9)) AS INSERT_TIMESTAMP_ODS_CDH_SYSTEM,
	CAST(UPDATE_TIMESTAMP_ASSET_SYS_REL_SFDC AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP_ODS_CDH_SYSTEM,

	----------------------------- AUDIT --------------------------------

    'INFOPRO,CDH' AS SOURCE_SYSTEM,
    'ODS_IFP_BIPAC, ODS_IFP_BIPACC, ODS_IFP_BIPTB, ODS_IFP_BIPCG, ODS_IFP_BIPCM, ODS_IFP_CUPASSACCT, ODS_IFP_CUPASSCODE,
	 ODS_CDH_ASSETPROFILE, ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP, ODS_CDH_SYSTEM' AS SOURCE_TABLES,
    CAST(bipac.OPERATION_TYPE AS VARCHAR(10)) AS OPERATION_TYPE,
    'ODS_IFP_BIPAC' AS PRIMARY_DATA_SOURCE,


	----- Populating as NULL for underived and dependent columns, will populate in future when the logic is clear
	
	CAST(NULL AS VARCHAR) AS CONTAINER_CATEGORY, -- Dependent on CORP_HIER
	CAST(NULL AS VARCHAR) AS DISPOSAL_SITE_NAME, -- Dependent on BIPLP
	CAST(NULL AS VARCHAR) AS GL_DIVISION_NUMBER, -- Dependent on CORP_HIER


	----------------------- DQ COLUMNS -----------------------------------------

	 CAST(NULL AS VARCHAR(50)) AS DQ_ERROR_CODE,
	 CAST('INSERT' AS VARCHAR) AS DQ_STATUS,
	 CAST(NULL AS VARCHAR) AS DQ_ERROR_MESSAGE,

	 ---------------------------- SOURCE PKs ---------------------------------

	 CAST(bipac.ODS_IFP_BIPAC_PK AS VARCHAR) AS ODS_IFP_BIPAC_PK,
	 CAST(bipacc.ODS_IFP_BIPACC_PK AS VARCHAR) AS ODS_IFP_BIPACC_PK,
	 CAST(biptb.ODS_IFP_BIPTB_PK AS VARCHAR) AS ODS_IFP_BIPTB_PK,
	 CAST(bipcg.ODS_IFP_BIPCG_PK AS VARCHAR) AS ODS_IFP_BIPCG_PK,
	 CAST(bipcm.ODS_IFP_BIPCM_PK AS VARCHAR) AS ODS_IFP_BIPCM_PK,
	 CAST(cupassacct.ODS_IFP_CUPASSACCT_PK AS VARCHAR) AS ODS_IFP_CUPASSACCT_PK,
	 CAST(cupasscode.ODS_IFP_CUPASSCODE_PK AS VARCHAR) AS ODS_IFP_CUPASSCODE_PK,
	 CAST(cuptb_rrq.ODS_IFP_CUPTB_PK AS VARCHAR) AS ODS_IFP_CUPTB_PK,
	 CAST(cdh_asset.ODS_CDH_ASSETPROFILE_PK AS VARCHAR) AS ODS_CDH_ASSETPROFILE_PK,
	 CAST(cdh_asset.ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP_PK AS VARCHAR) AS ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP_PK,
	 CAST(cdh_asset.ODS_CDH_SYSTEM_PK AS VARCHAR) AS ODS_CDH_SYSTEM_PK,
    

FROM CTE_BIPAC bipac
LEFT JOIN CTE_BIPACC bipacc
	ON  bipac.ACCOMP = bipacc.ACCOMP 
    AND bipac.ACACCT = bipacc.ACACCT
    AND bipac.ACSITE = bipacc.ACSITE
    AND bipac.ACCTGR = bipacc.ACCTGR

LEFT JOIN CTE_BIPCG bipcg    
    ON  bipac.ACCOMP = bipcg.CGCOMP
	AND bipac.ACACCT = bipcg.CGACCT
    AND bipac.ACMFCT = bipcg.CGMFCT
    AND bipac.ACCGRP = bipcg.CGCGRP

LEFT JOIN CTE_BIPCG_IND bipcg_ind    
	ON  bipac.ACCOMP = bipcg_ind.CGCOMP
	AND bipac.ACACCT = bipcg_ind.CGACCT
	AND bipac.ACMFCT = bipcg_ind.CGMFCT
	AND bipac.ACCGRP = bipcg_ind.CGCGRP	

LEFT JOIN CTE_BIPCM bipcm
    ON bipac.ACCOMP = bipcm.CMCOMP
    AND bipac.ACMFCT = bipcm.CMMFCT
    AND bipac.ACACCT = bipcm.CMACCT  

LEFT JOIN CTE_BIPTB biptb
    ON bipac.ACCOMP = biptb.TBDIVN
    AND bipac.ACCTTP = biptb.TBELEM


LEFT JOIN CTE_CUPASSACCT cupassacct
    ON bipac.ACCOMP = cupassacct.ASACOMP
    AND bipac.ACACCT = cupassacct.ASAACCT
    AND bipac.ACSITE = cupassacct.ASASITE
    AND bipac.ACCTGR = cupassacct.ASACTGR 
	--AND bipac.ACMFCT = cupassacct.ASAMFCT 

LEFT JOIN CTE_CUPASSCODE cupasscode
	ON cupassacct.ASAASCD = cupasscode.ASCASCD
	

LEFT JOIN CTE_CUPTB_RRQ cuptb_rrq
	ON bipac.ACRCPT = cuptb_rrq.TBELEM
	

LEFT JOIN CTE_CUPTB_MVT cuptb_mvt
    ON bipacc.ACFG05 = cuptb_mvt.TBELEM
    

LEFT JOIN CTE_CUPTB_DGC cuptb_dgc
	ON bipcg.CGSVC1 = cuptb_dgc.TBELEM
	

LEFT JOIN CTE_CUPTB_CCT cuptb_cct
	ON cuptb_cct.TBELEM = bipac.ACCTTP || LPAD(TO_CHAR(bipac.ACCTSZ, 'FM990.00'), 6, '0') || CASE WHEN LTRIM(RTRIM(bipac.ACCPAC)) = 'C' THEN 'C' ELSE '' END
	

LEFT JOIN CTE_CDH_ASSET cdh_asset
	ON bipac.ACCOMP = cdh_asset.InfoproDiv
	AND bipac.ACACCT = cdh_asset.Acct_Nbr
	AND bipac.ACSITE = cdh_asset.Site_Nbr
	AND bipac.ACCTGR = cdh_asset.CTGR_Nbr

-- LEFT JOIN CTE_CORPORATE_HIERARCHY corp_hier
-- 	ON bipac.ACCOMP = corp_hier.INFOPRO_DIVISION_NUMBER
-- 	AND bipac.ACREVD = corp_hier.REVENUE_DISTRIBUTION_CODE

WHERE 1=1

    {% if is_incremental() %}    
    AND (        
        bipac.UPDATE_TIMESTAMP_BIPAC >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_BIPAC') }}'
        OR bipacc.UPDATE_TIMESTAMP_BIPACC >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_BIPACC') }}'
        OR bipcg.UPDATE_TIMESTAMP_BIPCG >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_BIPCG') }}'
        OR bipcm.UPDATE_TIMESTAMP_BIPCM >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_BIPCM') }}'
        OR biptb.UPDATE_TIMESTAMP_BIPTB >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_BIPTB') }}'
        OR cupassacct.UPDATE_TIMESTAMP_CUPASSACCT >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_CUPASSACCT') }}'
        OR cupasscode.UPDATE_TIMESTAMP_CUPASSCODE >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_CUPASSCODE') }}'
        OR cuptb_rrq.UPDATE_TIMESTAMP_CUPTB >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_IFP_CUPTB') }}'
        OR cdh_asset.UPDATE_TIMESTAMP_ASSETPROFILE >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_CDH_ASSETPROFILE') }}'
        OR cdh_asset.UPDATE_TIMESTAMP_ASSET_SYS_REL_IFP >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_CDH_ASSET_SYSTEM_RELATIONSHIP') }}'
        OR cdh_asset.UPDATE_TIMESTAMP_SYSTEM >= '{{ get_max_event_time('UPDATE_TIMESTAMP_ODS_CDH_SYSTEM') }}'
    )
    {% endif %}


)
SELECT
    {{ generate_surrogate_key(['INFOPRO_DIVISION_NUMBER', 'ACCOUNT_NUMBER', 'SITE_NUMBER', 'CONTAINER_GROUP_NUMBER']) }} AS CDM_CONTAINER_PK,
    CONTAINER_COMPOSITE_KEY,
    INFOPRO_DIVISION_NUMBER,
    ACCOUNT_NUMBER,
    SITE_NUMBER,
    CONTAINER_GROUP_NUMBER,
    REVENUE_DISTRIBUTION_CODE,
    SITE_COMPOSITE_KEY,
    ACCOUNT_COMPOSITE_KEY,
    CONTAINER_NAME,
    IS_ACTIVE,
    ORIGINAL_START_DATE,
    LAST_SERVICE_DATE,
    REMOVAL_DATE,
    CLOSE_DATE,
    RATE_RESTRICTION_DATE,
    DISPOSAL_RATE_RESTRICTION_DATE,
    NEXT_RECURRING_CHARGE_GENERATION_DATE,
    BILLED_TO_DATE,
    SEASONAL_STOP_DATE,
    SEASONAL_RESTART_DATE,
    IS_SEASONAL_REMOVE_ROUTE,
    IS_SEASONAL_REMOVE_CONTAINER,
    IS_SEASONAL_RECURRING_CHARGE,
    CONTAINER_TYPE,
    CONTAINER_SIZE,
    CONTAINER_CATEGORY,
    HAS_COMPACTOR,
    IS_CONTAINER_OWNED,
    CONTAINER_COUNT,
    CONTAINER_QUANTITY_ON_SITE,
    YARDAGE,
    UNIT_OF_MEASURE,
    PRODUCT_DESCRIPTION,
    SHARED_CONTAINER_ID,
    IS_SHARED,
    PICKUP_PERIOD_TOTAL_LIFTS,
    PICKUP_PERIOD_LENGTH,
    PICKUP_PERIOD_UNIT,
    PICKUP_SCHEDULE,
    LIFT_SCHEDULE_DESCRIPTION,
    IS_ONCALL,
    MINIMUM_NUMBER_OF_LIFTS,
    MONDAY_LIFT_DAY,
    TUESDAY_LIFT_DAY,
    WEDNESDAY_LIFT_DAY,
    THURSDAY_LIFT_DAY,
    FRIDAY_LIFT_DAY,
    SATURDAY_LIFT_DAY,
    SUNDAY_LIFT_DAY,
    IS_MONDAY_REQUIRED,
    IS_TUESDAY_REQUIRED,
    IS_WEDNESDAY_REQUIRED,
    IS_THURSDAY_REQUIRED,
    IS_FRIDAY_REQUIRED,
    IS_SATURDAY_REQUIRED,
    IS_SUNDAY_REQUIRED,
    CONTRACT_GROUP_NUMBER,
    MUNICIPAL_FRANCHISE_CONTRACT,
    MUNICIPAL_CONTRACT_GROUP_NAME,
    MUNICIPAL_CONTRACT_TYPE,
    GRID_NUMBER,
    ACCOUNT_TYPE,
    RECURRING_CHARGE_FREQUENCY,
    RECURRING_MONTHS_ADV_BILL,
    SERVICE_MONTHS_ADV_BILL,
    RATE_TYPE,
    STOP_CODE,
    DISTRICT_CODE,
    IS_DISPOSAL_BILLABLE,
    IS_STD_DISPOSAL_BILLABLE,
    DISPOSAL_CODE,
    DISPOSAL_PRICE_CODE,
    DISPOSAL_SITE_NAME,
    DISPOSAL_RATE_PER_UNIT,
    DISPOSAL_ADJUSTMENT_VALUE,
    DISPOSAL_DOLLAR_ADJUSTMENT,
    DISPOSAL_ADJUSTMENT_CODE,
    DISPOSAL_COST_PER_REVENUE_CODE,
    DISPOSAL_TAX_APPLICATION_CODE,
    EXCESS_TON_AMOUNT,
    WASTE_STREAM_DESCRIPTION,
    SPECIAL_HANDLING_CODE,
    COMMODITY_CODE,
    FRANCHISE_FLAG,
    MUNICIPAL_FLAG,
    IS_PURCHASE_ORDER_REQUIRED,
    RECEIPT_REQUIRED_CODE,
    RECEIPT_REQUIRED_DESCRIPTION,
    HAS_CONTAINER_NOTES,
    ASSET_PROFILE_NUMBER,
    CONTAINER_SFDC_NUMBER,
    AVERAGE_WEIGHT,
    CITY_ACCOUNT_NUMBER,
    REMOTE_MONITOR_FLAG,
    MARKET_DESCRIPTION,
    MARKET_VERTICAL_INDICATOR,
    GL_DIVISION_NUMBER,
    SUMMARY_ROUTING_FLAG,
    DIGITAL_COMMUNICATIONS_FLAG,
    DIGITAL_COMMUNICATIONS_CODE,
    INDIVIDUAL_ACCOUNT_FLAG,
    INDIVIDUAL_INVOICES_REQUIRED_FLAG,
    ASSOCIATION_CODE,
    ASSOCIATION_DESC,
    ASSOCIATION_TYPE,
    CORPORATE_HIERARCHY_COMPOSITE_KEY,
    SOURCE_SYSTEM,
    SOURCE_TABLES,
    PRIMARY_DATA_SOURCE,
    ODS_IFP_BIPAC_PK,
    ODS_IFP_BIPACC_PK,
    ODS_IFP_BIPTB_PK,
    ODS_IFP_BIPCG_PK,
    ODS_IFP_BIPCM_PK,
    ODS_IFP_CUPASSACCT_PK,
    ODS_IFP_CUPASSCODE_PK,
    ODS_IFP_CUPTB_PK,
    ODS_CDH_ASSETPROFILE_PK,
    ODS_CDH_ASSETPROFILE_SYSTEM_RELATIONSHIP_PK,
    ODS_CDH_SYSTEM_PK,
    INSERT_TIMESTAMP_ODS_IFP_BIPAC,
    UPDATE_TIMESTAMP_ODS_IFP_BIPAC,
    INSERT_TIMESTAMP_ODS_IFP_BIPACC,
    UPDATE_TIMESTAMP_ODS_IFP_BIPACC,
    INSERT_TIMESTAMP_ODS_IFP_BIPCG,
    UPDATE_TIMESTAMP_ODS_IFP_BIPCG,
    INSERT_TIMESTAMP_ODS_IFP_BIPCM,
    UPDATE_TIMESTAMP_ODS_IFP_BIPCM,
    INSERT_TIMESTAMP_ODS_IFP_BIPTB,
    UPDATE_TIMESTAMP_ODS_IFP_BIPTB,
    INSERT_TIMESTAMP_ODS_IFP_CUPASSACCT,
    UPDATE_TIMESTAMP_ODS_IFP_CUPASSACCT,
    INSERT_TIMESTAMP_ODS_IFP_CUPASSCODE,
    UPDATE_TIMESTAMP_ODS_IFP_CUPASSCODE,
    INSERT_TIMESTAMP_ODS_IFP_CUPTB,
    UPDATE_TIMESTAMP_ODS_IFP_CUPTB,
    INSERT_TIMESTAMP_ODS_CDH_ASSETPROFILE,
    UPDATE_TIMESTAMP_ODS_CDH_ASSETPROFILE,
    INSERT_TIMESTAMP_ODS_CDH_ASSET_SYSTEM_RELATIONSHIP,
    UPDATE_TIMESTAMP_ODS_CDH_ASSET_SYSTEM_RELATIONSHIP,
    INSERT_TIMESTAMP_ODS_CDH_SYSTEM,
    UPDATE_TIMESTAMP_ODS_CDH_SYSTEM,
    CAST(CTE_BATCH_ID.BATCH_ID AS BIGINT) AS CDM_INS_BATCH_ID,
    CAST(CTE_BATCH_ID.BATCH_ID AS BIGINT) AS CDM_UPD_BATCH_ID,
    CAST(CTE_BATCH_ID.TIME_STAMP AS TIMESTAMP_NTZ(9)) AS CDM_INSERT_TIMESTAMP,
    CAST(CTE_BATCH_ID.TIME_STAMP AS TIMESTAMP_NTZ(9)) AS CDM_UPDATE_TIMESTAMP,
    OPERATION_TYPE,
    DQ_STATUS,
    DQ_ERROR_CODE,
    DQ_ERROR_MESSAGE,
    {{ generate_hash_change(relation = this) }} AS HASH_CHANGE,
    {{ generate_hash_full(relation = this) }} AS HASH_FULL
FROM CTE_TRANSFORMATION_CONTAINER
JOIN CTE_BATCH_ID ON 1=1


